Repository kokkos/kokkos, pull requests merged in 2018-02, with the labels that each got.

#1428 DualView: Rename 'extents' to 'extent'
  containers/src/Kokkos_DualView.hpp
Labels: DevelopOnly, InDevelop, bug, bug - fix pushed to develop branch

#1439 Add support for Cavium ThunderX2 Processor
  Makefile.kokkos
  generate_makefile.bash
Labels: Compiler Support, enhancement

#1441 Fix unit test compile on OS X
  core/unit_test/TestTeamVector.hpp
Labels: BLOCKS PROMOTION, bug

#1444 Fix compilation with profiling disabled
  Makefile.kokkos
  core/src/impl/Kokkos_Profiling_Interface.cpp
Labels: BLOCKS PROMOTION, bug
