Repository kokkos/kokkos, pull requests merged in 2018-05, with the labels that each got.

#1603 Fix clang version check
  Makefile.kokkos
Labels: BLOCKS PROMOTION, bug

#1606 Fix shadow warning with Clang+CUDA
  containers/src/Kokkos_DynamicView.hpp
Labels: enhancement

#1609 Backwards-compatible reducer namespace
  core/src/Kokkos_Parallel_Reduce.hpp
Labels: enhancement

#1628 View: Loosen dyn_rank check for non-void specialization types
  core/src/Kokkos_View.hpp
Labels: BLOCKS PROMOTION

#1638 Add CMake support for new deep_copy ETI
  cmake/kokkos_options.cmake
  cmake/kokkos_settings.cmake
  core/src/CMakeLists.txt
  core/src/Cuda/Kokkos_Cuda_ViewCopyETIAvail.hpp
  core/src/Cuda/Kokkos_Cuda_ViewCopyETIDecl.hpp
  core/src/OpenMP/Kokkos_OpenMP_ViewCopyETIAvail.hpp
  core/src/OpenMP/Kokkos_OpenMP_ViewCopyETIDecl.hpp
  core/src/ROCm/Kokkos_ROCm_ViewCopyETIAvail.hpp
  core/src/ROCm/Kokkos_ROCm_ViewCopyETIDecl.hpp
  core/src/Serial/Kokkos_Serial_ViewCopyETIAvail.hpp
  core/src/Serial/Kokkos_Serial_ViewCopyETIDecl.hpp
  core/src/Threads/Kokkos_Threads_ViewCopyETIAvail.hpp
  core/src/Threads/Kokkos_Threads_ViewCopyETIDecl.hpp
  core/src/eti/CMakeLists.txt
  core/src/eti/Cuda/CMakeLists.txt
  core/src/eti/OpenMP/CMakeLists.txt
  core/src/eti/ROCm/CMakeLists.txt
  core/src/eti/Serial/CMakeLists.txt
  core/src/eti/Threads/CMakeLists.txt
Labels: BLOCKS PROMOTION
