Repository kokkos/kokkos, pull requests merged in 2018-03, with the labels that each got.

#1453 finalize(): Move finalize_hooks code to finalize_internal
  core/src/impl/Kokkos_Core.cpp
Labels: BLOCKS PROMOTION

#1456 Fix for issue #1455: single statements need warp barrier
  config/test_all_sandia
  core/src/Cuda/Kokkos_Cuda_Team.hpp
  core/src/Cuda/Kokkos_Cuda_Version_9_8_Compatibility.hpp
  core/unit_test/Makefile
Labels: BLOCKS PROMOTION

#1460 Allow KOKKOS_ARCH with commas in CMake
  cmake/kokkos_settings.cmake
Labels: BLOCKS PROMOTION

#1462 MDRangePolicy: Fix tile dims when range span is 0
  core/src/KokkosExp_MDRangePolicy.hpp
Labels: BLOCKS PROMOTION

#1467 Correct some of the promotion documentation
  doc/kokkos-promotion.txt
Labels: Documentation

#1503 Fix out-of-bounds when bins are empty
  algorithms/src/Kokkos_Sort.hpp
Labels: bug
