Repository kokkos/kokkos, pull requests merged in 2018-04, with the labels that each got.

#1550 Fix file list in CMake unit tests
  core/unit_test/CMakeLists.txt
Labels: bug

#1579 Add missing header in Kokkos_Array.hpp
  core/src/Kokkos_Array.hpp
Labels: BLOCKS PROMOTION, bug

#1584 Still define HAVE macros with deprecated code on
  core/src/impl/Kokkos_OldMacros.hpp
Labels: BLOCKS PROMOTION
