Repository kokkos/kokkos, pull requests merged in 2020-07, with the labels that each got.

#3106 Apply [[noreturn]] to Kokkos::abort when applicable
  core/src/Cuda/Kokkos_Cuda_abort.hpp
  core/src/impl/Kokkos_Error.hpp
Labels: enhancement

#3116 First attempt at automated refactoring with clang-tidy + clang-format.
  containers/src/impl/Kokkos_Functional_impl.hpp
  core/src/KokkosExp_MDRangePolicy.hpp
  core/src/Kokkos_AnonymousSpace.hpp
  core/src/Kokkos_Array.hpp
  core/src/Kokkos_Complex.hpp
  core/src/Kokkos_Concepts.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_Crs.hpp
  core/src/Kokkos_ExecPolicy.hpp
  core/src/Kokkos_HostSpace.hpp
  core/src/Kokkos_Layout.hpp
  core/src/Kokkos_MemoryPool.hpp
  core/src/Kokkos_MemoryTraits.hpp
  core/src/Kokkos_Pair.hpp
  core/src/Kokkos_Parallel.hpp
  core/src/Kokkos_Parallel_Reduce.hpp
  core/src/Kokkos_ScratchSpace.hpp
  core/src/Kokkos_Serial.hpp
  core/src/Kokkos_TaskScheduler.hpp
  core/src/Kokkos_View.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp
  core/src/OpenMP/Kokkos_OpenMP_Team.hpp
  core/src/OpenMP/Kokkos_OpenMP_WorkGraphPolicy.hpp
  core/src/impl/KokkosExp_Host_IterateTile.hpp
  core/src/impl/Kokkos_Atomic_Exchange.hpp
  core/src/impl/Kokkos_Atomic_View.hpp
  core/src/impl/Kokkos_ConcurrentBitset.hpp
  core/src/impl/Kokkos_FunctorAdapter.hpp
  core/src/impl/Kokkos_FunctorAnalysis.hpp
  core/src/impl/Kokkos_HostSpace.cpp
  core/src/impl/Kokkos_HostSpace_deepcopy.cpp
  core/src/impl/Kokkos_Profiling_C_Interface.h
  core/src/impl/Kokkos_Serial_WorkGraphPolicy.hpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_Traits.hpp
  core/src/impl/Kokkos_ViewArray.hpp
  core/src/impl/Kokkos_ViewCtor.hpp
  core/src/impl/Kokkos_ViewLayoutTiled.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/src/impl/Kokkos_ViewUniformType.hpp
  core/src/impl/Kokkos_Volatile_Load.hpp
  core/unit_test/TestViewAPI.hpp
Labels: BLOCKS PROMOTION

#3171 Do not initialize/finalize profiling inside Cuda and HIP backends
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/HIP/Kokkos_HIP_Space.cpp
Labels: BLOCKS PROMOTION

#3159 Added names of Views to the different View initialize/free kernels
  core/src/impl/Kokkos_ViewArray.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/CMakeLists.txt
Labels: BLOCKS PROMOTION

#3162 ScatterView: fix for OpenmpTarget remove inheritance from reducers
  containers/src/Kokkos_ScatterView.hpp
  core/src/impl/Kokkos_Atomic_Generic_Secondary.hpp
Labels: BLOCKS PROMOTION

#3165 Allow larger block size in HIP
  core/src/HIP/Kokkos_HIP_BlockSize_Deduction.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
  core/src/Kokkos_Macros.hpp
  core/unit_test/TestTeamVector.hpp
  core/unit_test/hip/TestHIP_ScanUnit.cpp
Labels: BLOCKS PROMOTION

#3154 Add support for shuffle reduction for the HIP backend
  core/src/HIP/Kokkos_HIP_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_ReduceScan.hpp
Labels: BLOCKS PROMOTION

#3169 Omptarget Updates
  .jenkins
  Makefile.kokkos
  cmake/kokkos_arch.cmake
  cmake/kokkos_compiler_id.cmake
  cmake/kokkos_enable_devices.cmake
  cmake/kokkos_functions.cmake
  core/perf_test/CMakeLists.txt
  core/src/Kokkos_Macros.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_MDRange.hpp
  core/src/impl/Kokkos_ClockTic.hpp
  core/src/impl/Kokkos_Memory_Fence.hpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestReduce.hpp
  core/unit_test/TestReduceCombinatorical.hpp
  core/unit_test/TestViewLayoutStrideAssignment.hpp
  core/unit_test/openmptarget/TestOpenMPTarget_Reductions.cpp
  core/unit_test/openmptarget/TestOpenMPTarget_TeamReductionScan.cpp
Labels: BLOCKS PROMOTION

#3170 Fix CUDA stream memory leak
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Kokkos_Cuda.hpp
  core/unit_test/cuda/TestCuda_InterOp_Streams.cpp
Labels: BLOCKS PROMOTION

#3135 Fix issues with project(Kokkos) when building Kokkos as subproject, add more testing
  .jenkins
  CMakeLists.txt
  cmake/kokkos_install.cmake
  example/build_cmake_in_tree/CMakeLists.txt
  example/build_cmake_in_tree/cmake_example.cpp
  example/build_cmake_in_tree/foo.f
  example/build_cmake_installed/CMakeLists.txt
  example/build_cmake_installed/cmake_example.cpp
Labels: BLOCKS PROMOTION

#3191 Fix configuring with OpenMPTarget and without CUDA
  cmake/kokkos_arch.cmake
Labels: BLOCKS PROMOTION

#3187 Documentation updates: touch up BUILD.md, add Spack.md
  BUILD.md
  README.md
  Spack.md
  config/yaml/volta.yaml
  example/build_cmake_in_tree/CMakeLists.txt
  example/build_cmake_installed/CMakeLists.txt
Labels: BLOCKS PROMOTION

#3186 Improve support for nvcc_wrapper with exotic host compiler
  cmake/kokkos_arch.cmake
  cmake/kokkos_test_cxx_std.cmake
Labels: BLOCKS PROMOTION

#3208 Adding threadfence for lock based atomics
  core/src/Kokkos_Atomic.hpp
  core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
  core/src/impl/Kokkos_Atomic_Compare_Exchange_Weak.hpp
  core/src/impl/Kokkos_Atomic_Exchange.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Add.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
  core/src/impl/Kokkos_Atomic_Generic.hpp
Labels: BLOCKS PROMOTION, bug

#3182 Force enabling one architecture for HIP
  cmake/kokkos_arch.cmake
Labels: BLOCKS PROMOTION

#3223 Don't force NDEBUG for HIP >= 3.6.0
  .jenkins
  core/src/Kokkos_Macros.hpp
Labels: BLOCKS PROMOTION
