Repository kokkos/kokkos, pull requests merged in 2020-11, with the labels that each got.

#3560 [CUDA] Re-set preferred cache configuration if it changed
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
Labels: bug

#3588 Add atomic functions for unsigned long long using gcc built-in
  core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
  core/src/impl/Kokkos_Atomic_Compare_Exchange_Weak.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Add.hpp
  core/src/impl/Kokkos_Atomic_Fetch_And.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
Labels: BLOCKS PROMOTION

#3591 Fixup MDRangePolicy construction from Kokkos arrays
  core/src/KokkosExp_MDRangePolicy.hpp
  core/unit_test/TestPolicyConstruction.hpp
Labels: BLOCKS PROMOTION, DevelopOnly

#3595 Workaround GraphNodeRef static_assert that does not compile with IBM XL
  core/src/Kokkos_GraphNode.hpp
  core/src/Kokkos_Macros.hpp
  core/src/impl/Kokkos_BitOps.hpp
  core/src/impl/Kokkos_HostThreadTeam.hpp
Labels: BLOCKS PROMOTION, DevelopOnly

#3616 Update Makefiles for benchmarks, and unit tests
  Makefile.kokkos
  benchmarks/atomic/Makefile
  benchmarks/benchmark_suite/scripts/run_tests.bash
  benchmarks/bytes_and_flops/Makefile
  benchmarks/gather/Makefile
  benchmarks/gups/Makefile
  benchmarks/gups/gups-kokkos.cpp
  benchmarks/policy_performance/Makefile
  benchmarks/stream/Makefile
  benchmarks/stream/stream-kokkos.cpp
  core/unit_test/Makefile
Labels: BLOCKS PROMOTION

#3617 Fix SYCL memory access in allocation
  core/src/SYCL/Kokkos_SYCL_Space.cpp
Labels: BLOCKS PROMOTION

#3610 Fix teamthreadrange scan
  core/src/Cuda/Kokkos_Cuda_Team.hpp
  core/src/HIP/Kokkos_HIP_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/Makefile
  core/unit_test/TestTeamScan.hpp
Labels: BLOCKS PROMOTION
