Repository kokkos/kokkos, pull requests merged in 2021-09, with the labels that each got.

#4156 Update support for cuda reductions to work with types < 4 bytes in size
  core/src/Cuda/Kokkos_Cuda_Half.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel.hpp
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/impl/Kokkos_FunctorAdapter.hpp
  core/unit_test/TestHalfOperators.hpp
  core/unit_test/TestNonTrivialScalarTypes.hpp
  core/unit_test/TestReducers.hpp
  core/unit_test/TestReducers_d.hpp
Labels: Enhancement, Blocks Promotion

#4273 Use std::memcpy in USMObjectMem instead of placment new
  core/src/SYCL/Kokkos_SYCL_Instance.cpp
  core/src/SYCL/Kokkos_SYCL_Instance.hpp
  core/src/impl/Kokkos_HostSharedPtr.hpp
  core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
Labels: Blocks Promotion

#4282 Desul NVIDIA ASM Atomics update
  core/src/CMakeLists.txt
  core/src/Kokkos_Atomics_Desul_Volatile_Wrapper.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/desul/atomics/cuda/CUDA_asm.hpp
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc_forceglobal
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc_generic
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc_isglobal
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_fetch_op.inc_predicate
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc_forceglobal
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc_generic
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc_isglobal
  core/src/desul/atomics/cuda/cuda_cc7_asm_atomic_op.inc_predicate
Labels: Enhancement, Blocks Promotion

#4207 Avoid allocations in resize and realloc
  cmake/kokkos_arch.cmake
  containers/src/Kokkos_DualView.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/Kokkos_Layout.hpp
Labels: Blocks Promotion

#4278 Fixes constexpr errors with frounding-math on gcc < 10.
  core/src/Kokkos_Tuners.hpp
Labels: Blocks Promotion

#4292 Adding missing memory fence to serial exec space fence.
  core/src/Kokkos_Serial.hpp
Labels: Bug, Blocks Promotion

#4291 Fix using external SYCL queues in tests
  core/unit_test/sycl/TestSYCL_InterOp_Init.cpp
  core/unit_test/sycl/TestSYCL_TeamScratchStreams.cpp
Labels: Blocks Promotion

#4299 Intel 17 atomic illegal instruction fix
  algorithms/unit_tests/TestRandom.hpp
Labels: Blocks Promotion

#4302 Reenabling Desul atomics for Intel 17
  cmake/kokkos_enable_options.cmake
  containers/unit_tests/TestScatterView.hpp
Labels: Blocks Promotion

#4142 Replace arg_policy.team_size_max with Kokkos::Impl::cuda_get_max_block_size in Cuda::ParallelReduce
  core/src/Cuda/Kokkos_Cuda_Parallel.hpp
Labels: Blocks Promotion

#4306 Replace remaining atomics in tasking with seqcst atomics
  core/src/Kokkos_Atomic.hpp
  core/src/Kokkos_TaskScheduler.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_TaskNode.hpp
  core/src/impl/Kokkos_TaskQueue.hpp
  core/src/impl/Kokkos_TaskQueueCommon.hpp
  core/src/impl/Kokkos_TaskQueueMemoryManager.hpp
  core/src/impl/Kokkos_TaskQueueMultiple.hpp
  core/src/impl/Kokkos_TaskQueue_impl.hpp
Labels: Blocks Promotion

#4311 CUDA MDRange 6D Test: add LaunchBounds
  core/unit_test/TestMDRange.hpp
Labels: Blocks Promotion
