Repository kokkos/kokkos, pull requests merged in 2021-03, with the labels that each got.

#3808 OpenMPTarget: Changes to the hierarchical parallelism
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
Labels: [WIP]

#3824 Introduce HostSharedPtr to manage m_space_instance for Cuda/HIP/SYCL
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/HIP/Kokkos_HIP_Space.cpp
  core/src/Kokkos_Cuda.hpp
  core/src/Kokkos_HIP_Space.hpp
  core/src/Kokkos_SYCL.hpp
  core/src/SYCL/Kokkos_SYCL.cpp
  core/src/impl/Kokkos_HostSharedPtr.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestHostSharedPtr.hpp
  core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
Labels: BLOCKS PROMOTION

#3843 Try compiling C++14 check with C++14 support and print error message
  cmake/kokkos_test_cxx_std.cmake
Labels: BLOCKS PROMOTION

#3822 DualView sync's on ExecutionSpaces
  containers/src/Kokkos_DualView.hpp
  containers/unit_tests/TestDualView.hpp
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/Kokkos_CudaSpace.hpp
Labels: BLOCKS PROMOTION

#3812 V1.1 Tools Interface: incremental, action-based
  core/src/impl/Kokkos_Profiling.cpp
  core/src/impl/Kokkos_Profiling_C_Interface.h
  core/src/impl/Kokkos_Profiling_Interface.hpp
Labels: BLOCKS PROMOTION

#3818 SYCL outer TeamPolicy parallel_reduce
  core/perf_test/PerfTest_CustomReduction.cpp
  core/perf_test/PerfTest_ExecSpacePartitioning.cpp
  core/src/SYCL/Kokkos_SYCL_Parallel_Team.hpp
  core/src/SYCL/Kokkos_SYCL_Team.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestCXX11.hpp
  core/unit_test/TestLocalDeepCopy.hpp
  core/unit_test/TestReductions_DeviceView.hpp
  core/unit_test/TestTeam.hpp
  core/unit_test/TestTeamBasic.hpp
  core/unit_test/TestTeamReductionScan.hpp
  core/unit_test/TestTeamTeamSize.hpp
  core/unit_test/TestTeamVector.hpp
  core/unit_test/default/TestDefaultDeviceType_a3.cpp
  core/unit_test/default/TestDefaultDeviceType_b3.cpp
  core/unit_test/default/TestDefaultDeviceType_c3.cpp
  core/unit_test/sycl/TestSYCL_InterOp_Streams.cpp
  example/tutorial/Hierarchical_Parallelism/01_thread_teams/thread_teams.cpp
  example/tutorial/Hierarchical_Parallelism/01_thread_teams_lambda/thread_teams_lambda.cpp
  example/tutorial/Hierarchical_Parallelism/02_nested_parallel_for/nested_parallel_for.cpp
  example/tutorial/Hierarchical_Parallelism/CMakeLists.txt
Labels: BLOCKS PROMOTION

#3833 Implement UniqueToken for SYCL
  containers/src/impl/Kokkos_UnorderedMap_impl.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestUnorderedMap.hpp
  core/src/SYCL/Kokkos_SYCL_Instance.cpp
  core/src/SYCL/Kokkos_SYCL_Instance.hpp
  core/src/SYCL/Kokkos_SYCL_UniqueToken.hpp
  core/src/decl/Kokkos_Declare_SYCL.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestUniqueToken.hpp
  core/unit_test/TestView_64bit.hpp
  scripts/docker/Dockerfile.sycl
Labels: BLOCKS PROMOTION

#3857 DualView.template view() better matches for Devices in UVMSpace cases
  containers/src/Kokkos_DualView.hpp
  containers/unit_tests/TestDualView.hpp
Labels: BLOCKS PROMOTION

#3881 Address intel 17 ICE
  core/src/impl/Kokkos_SharedAlloc_timpl.hpp
Labels: BLOCKS PROMOTION

#3886 Don't use a static variable in HIPInternal::scratch_space
  core/src/HIP/Kokkos_HIP_Instance.cpp
Labels: [WIP], bug
