Repository kokkos/kokkos, pull requests merged in 2022-05, with the labels that each got.

#5002 Drop `__CUDA_ARCH__` macro guard in device function `cuda_inter_block_reduction`
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
Labels: Refactor

#5008 Fix racing condition in HIPParallelLaunch
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: Bug

#5003 Refactor `CudaTeamMember` implementation to avoid `#ifdef __CUDA_ARCH__`
  core/src/Cuda/Kokkos_Cuda_Team.hpp
Labels: Refactor

#5001 Refactor `BitOps` to not rely on `__CUDA_ARCH__` macro
  core/src/impl/Kokkos_BitOps.hpp
Labels: Refactor

#5011 Remove KOKKOS_ENABLE_POSIX_MEMALIGN
  core/src/Kokkos_Macros.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_HostSpace.cpp
Labels: Question

#5022 Replace `#ifdef __CUDA_ARCH__` in `cast_{to,from}_half()`
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
Labels: Refactor

#5023 Refactor Cuda and HIP specializations of `Random_UniqueIndex`
  algorithms/src/Kokkos_Random.hpp
Labels: Refactor

#5028 Fixed an incorrect struct initialization
  core/src/HIP/Kokkos_HIP_Locks.cpp
Labels: Bug, Patch Release

#5036 Remove unused view ctor property `Impl::NullSpace_t`
  core/src/impl/Kokkos_ViewCtor.hpp
Labels: Refactor

#5045 #5025: Fix ScatterMin/ScatterMax to use proper atomics
  containers/src/Kokkos_ScatterView.hpp
Labels: Bug

#5046 #5025: Fix ScatterMin/ScatterMax to use proper atomics (3.6.01 cherry-pick)
  containers/src/Kokkos_ScatterView.hpp
Labels: Bug, Patch Release

#5062 Make unique token unit tests print max reuse on failure only
  core/unit_test/TestUniqueToken.hpp
Labels: Refactor

#5058 Refactor execution space unit test
  core/unit_test/TestExecutionSpace.hpp
Labels: Refactor
