Repository kokkos/kokkos, pull requests merged in 2022-11, with the labels that each got.

#5605 Fix cudaErrorInvalidDeviceFunction error caused by an uninstantiated functor
  core/src/impl/Kokkos_ViewMapping.hpp
Labels: Blocks Promotion

#5625 SYCL: Set RangePolicy default chunk_size to 1
  core/src/Kokkos_ExecPolicy.hpp
Labels: Blocks Promotion

#5627 Remove pre C++17 workarounds and use fold expressions
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_Graph.hpp
  core/src/Kokkos_SYCL.hpp
  core/src/impl/Kokkos_Combined_Reducer.hpp
  core/src/impl/Kokkos_Utilities.hpp
  core/unit_test/TestUtilities.hpp
  core/unit_test/tools/include/ToolTestingUtilities.hpp
Labels: Refactor

#5630 Reuse code for detecting MPI context
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
  core/src/impl/Kokkos_CPUDiscovery.cpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_DeviceManagement.hpp
  core/unit_test/TestCTestDevice.cpp
Labels: Enhancement, Refactor

#5622 [3.7.01] Fix initialization of Cuda lock arrays
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
  core/src/Cuda/Kokkos_Cuda_Locks.cpp
  core/src/Cuda/Kokkos_Cuda_Locks.hpp
  tpls/desul/include/desul/atomics/Lock_Array_Cuda.hpp
  tpls/desul/src/Lock_Array_CUDA.cpp
Labels: Blocks Promotion, Patch Release
