Repository kokkos/kokkos, pull requests merged in 2022-12, with the labels that each got.

#5645 Prefer C++11 built-in support for threads to detect the number of processors
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
  core/src/impl/Kokkos_CPUDiscovery.cpp
  core/src/impl/Kokkos_CPUDiscovery.hpp
Labels: Refactor

#5522 Remove support for MI25 and add support for NAVI 1030
  Makefile.kokkos
  cmake/KokkosCore_config.h.in
  cmake/kokkos_arch.cmake
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_ReduceScan.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestSharedSpace.cpp
  generate_makefile.bash
Labels: Blocks Promotion

#5664 Cleanup `CudaLDGFetch` class template
  core/src/Cuda/Kokkos_Cuda_View.hpp
Labels: Refactor

#5673 Add architecture flags for MSVC
  cmake/kokkos_arch.cmake
  cmake/kokkos_functions.cmake
Labels: CHANGELOG

#5660 Work around CUDA+Clang Thrust issue
  algorithms/src/Kokkos_Sort.hpp
Labels: Blocks Promotion

#5672 Fix default memory order for sycl::atomic_ref
  tpls/desul/include/desul/atomics/Adapt_SYCL.hpp
Labels: Blocks Promotion

#5598 Refactor Policy constructor tests
  core/unit_test/CMakeLists.txt
  core/unit_test/TestCommonPolicyConstructors.hpp
  core/unit_test/TestCommonPolicyInterface.hpp
  core/unit_test/TestInit.hpp
  core/unit_test/TestMDRangePolicyConstructors.hpp
  core/unit_test/TestPolicyConstruction.hpp
  core/unit_test/TestRangePolicyConstructors.hpp
  core/unit_test/TestTeamPolicyConstructors.hpp
Labels: Refactor

#5680 Refactor `Impl::ParallelReduce<RangePolicy, OpenACC>` to reduce code duplication
  core/src/OpenACC/Kokkos_OpenACC_Macros.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
Labels: Refactor

#5678 #2873: Check for presence of execinfo.h before enabling its use for stack tracing
  core/src/Kokkos_Macros.hpp
Labels: CHANGELOG

#5691 Update nvcc_wrapper default arch to work with CUDA 12
  bin/nvcc_wrapper
Labels: Blocks Promotion, Patch Release, CHANGELOG, Backend - CUDA

#5715 Add README.md explaining the incremental tests
  core/unit_test/incremental/README.md
Labels: Documentation

#5709 Fix CUDA lock arrays
  core/src/Cuda/Kokkos_Cuda_Locks.hpp
  tpls/desul/include/desul/atomics/Lock_Array_CUDA.hpp
Labels: Blocks Promotion, Backend - CUDA
