Repository kokkos/kokkos, pull requests merged in 2022-08, with the labels that each got.

#5305 Workaround intel/19 OMP internal compiler errors in Trilinos
  core/src/Kokkos_OpenMP.hpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
Labels: Blocks Promotion

#5273 inline constexpr bool is_CONCEPT_v variables added to match C++17 traits
  core/src/Kokkos_Concepts.hpp
  core/unit_test/TestConcepts.hpp
Labels: C++17

#5330 Print OpenMP warnings to the standard error stream
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
Labels: Enhancement, Refactor

#5324 #5312: Revert #3580 and try a different workaround (3.7 RC branch)
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
Labels: Blocks Promotion

#5337 Kokkos: Fix install( ... DESTINATION ... ) dir (#10810)
  CMakeLists.txt
  core/src/impl/CMakeLists.txt
Labels: Blocks Promotion

#5339 Fix missing linker language for SIMD
  CMakeLists.txt
  simd/src/CMakeLists.txt
Labels: Blocks Promotion

#5345 Fix null deref in SharedAllocationRecord::print_records
  core/src/impl/Kokkos_SharedAlloc.cpp
Labels: Bug

#5367 Refactor `InitializationSettings` class to leverage std::optional
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_InitializationSettings.hpp
Labels: Refactor

#5327 Enable automatic detection of arch when enabling 'HIP' with 'hipcc'
  cmake/kokkos_arch.cmake
Labels: Bug

#5368 Prefer `std::void_t` now that C++17 is available
  core/src/Kokkos_DetectionIdiom.hpp
  core/src/impl/Kokkos_Utilities.hpp
  core/unit_test/tools/include/ToolTestingUtilities.hpp
Labels: Refactor

#5370 Rename trait `Impl::{identity -> type_identity}`
  core/src/Cuda/Kokkos_Cuda_GraphNodeKernel.hpp
  core/src/Kokkos_Atomic.hpp
  core/src/Kokkos_ExecPolicy.hpp
  core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
  core/src/impl/Kokkos_Atomic_Exchange.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Add.hpp
  core/src/impl/Kokkos_Atomic_Fetch_And.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
  core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
  core/src/impl/Kokkos_Utilities.hpp
Labels: Refactor

#5377 Fix initialization for array reductions
  core/src/impl/Kokkos_FunctorAnalysis.hpp
  core/unit_test/TestMDRange.hpp
Labels: Blocks Promotion

#5390 [3.7] Force creation of the cuda_deep_space instance during init
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
Labels: Bug, Blocks Promotion

#5384 [3.7] #5382: Deprecate overloads of Kokkos::sort() taking parameter 'bool always_use_kokkos_sort'
  CHANGELOG.md
  algorithms/src/Kokkos_Sort.hpp
  algorithms/unit_tests/TestSort.hpp
Labels: Blocks Promotion

#5317 Team- and thread-level sort, sort_by_key
  algorithms/src/Kokkos_NestedSort.hpp
  algorithms/src/Kokkos_Sort.hpp
  algorithms/unit_tests/CMakeLists.txt
  algorithms/unit_tests/TestNestedSort.hpp
Labels: Enhancement
