Repository kokkos/kokkos, pull requests merged in 2022-03, with the labels that each got.

#4830 Fix for default definition of Kokkos_ENABLE_PTHREAD
  cmake/kokkos_tpls.cmake
Labels: Blocks Promotion

#4841 cmake: Replace Enable_PTHREAD with ENABLE_THREADS
  .github/workflows/osx.yml
  BUILD.md
  cmake/Modules/FindTPLPTHREAD.cmake
  cmake/Modules/FindTPLTHREADS.cmake
  cmake/kokkos_enable_devices.cmake
  cmake/kokkos_tpls.cmake
  core/src/CMakeLists.txt
Labels: Blocks Promotion

#4800 Cleanup View access
  core/src/Kokkos_View.hpp
  core/src/impl/Kokkos_Utilities.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestViewOperatorParens.cpp
Labels: Refactor

#4869 Fix scratch_locks pointer not getting set when using reducers
  core/src/Cuda/Kokkos_Cuda_Parallel.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
  core/unit_test/TestTeam.hpp
Labels: Blocks Promotion

#4872 Fix HIP version when printing the configuration
  core/src/HIP/Kokkos_HIP_Instance.cpp
Labels: Bug

#4197 compile time view subscriber and dynamic view hooks
  core/src/Kokkos_Concepts.hpp
  core/src/Kokkos_View.hpp
  core/src/View/Hooks/Kokkos_ViewHooks.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestInterOp.cpp
  core/unit_test/TestViewHooks.hpp
Labels: Feature Request

#4876 Fixup `View::access()` truncate parameter pack
  core/src/Kokkos_View.hpp
Labels: Refactor

#4920 Cleanup `<stdexcept>` header includes
  containers/src/Kokkos_Bitset.hpp
  containers/src/Kokkos_UnorderedMap.hpp
  containers/unit_tests/TestDynViewAPI.hpp
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/HIP/Kokkos_HIP_Space.cpp
  core/src/Kokkos_HPX.hpp
  core/src/impl/Kokkos_MultipleTaskQueue.hpp
  core/src/impl/Kokkos_SingleTaskQueue.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_TaskNode.hpp
  core/src/impl/Kokkos_TaskQueue.hpp
  core/src/impl/Kokkos_TaskQueueCommon.hpp
  core/src/impl/Kokkos_TaskQueueMemoryManager.hpp
  core/src/impl/Kokkos_TaskQueueMultiple.hpp
  core/src/impl/Kokkos_TaskResult.hpp
  core/src/impl/Kokkos_hwloc.cpp
  core/unit_test/TestConcurrentBitset.hpp
  core/unit_test/TestExecSpacePartitioning.hpp
  core/unit_test/TestInit.hpp
  core/unit_test/TestIrregularLayout.hpp
  core/unit_test/TestLocalDeepCopy.hpp
  core/unit_test/TestPolicyConstruction.hpp
  core/unit_test/TestReduce.hpp
  core/unit_test/TestReduceCombinatorical.hpp
  core/unit_test/TestReducers.hpp
  core/unit_test/TestSharedAlloc.hpp
  core/unit_test/TestTeam.hpp
  core/unit_test/TestTeamTeamSize.hpp
  core/unit_test/TestUtilities.hpp
  core/unit_test/TestViewAPI.hpp
  core/unit_test/TestViewAPI_e.hpp
  core/unit_test/TestViewLayoutStrideAssignment.hpp
  core/unit_test/TestViewMapping_a.hpp
  core/unit_test/TestViewMapping_b.hpp
  core/unit_test/TestViewMapping_subview.hpp
  core/unit_test/TestViewOfClass.hpp
  core/unit_test/TestViewSpaceAssign.hpp
  core/unit_test/TestViewSubview.hpp
Labels: Refactor
