Repository kokkos/kokkos, pull requests merged in 2022-04, with the labels that each got.

#4934 Use synchronous Memcpy when using DeepCopy
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/HIP/Kokkos_HIP_Space.cpp
Labels: Blocks Promotion

#4946 Fix bug in explicit specialization of RuntimeCheckMemoryAccessViolation
  core/src/Kokkos_Core_fwd.hpp
Labels: Bug

#4957 Deprecate `Kokkos::is_reducer_type`
  core/src/Kokkos_HPX.hpp
  core/src/Kokkos_Parallel_Reduce.hpp
  core/src/Kokkos_Serial.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_MDRange.hpp
  core/src/Threads/Kokkos_Threads_Parallel.hpp
Labels: Refactor, Deprecate

#4930 Add option to optimize for CPU architecture of local machine
  .github/workflows/continuous-integration-workflow-hpx.yml
  .github/workflows/continuous-integration-workflow.yml
  .github/workflows/osx.yml
  .jenkins
  BUILD.md
  appveyor.yml
  cmake/kokkos_arch.cmake
Labels: Question
