Repository kokkos/kokkos, pull requests merged in 2022-02, with the labels that each got.

#4740 algorithms/unit_tests: Skip correctness checks for bhalf
  algorithms/unit_tests/TestRandom.hpp
Labels: Bug

#4690 Desul: Add ScopeCaller
  core/src/Kokkos_Atomics_Desul_Volatile_Wrapper.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/desul/.clang-format
  core/src/desul/atomics/Common.hpp
  core/src/desul/atomics/Compare_Exchange.hpp
  core/src/desul/atomics/Compare_Exchange_ScopeCaller.hpp
  core/src/desul/atomics/Generic.hpp
Labels: Blocks Promotion

#4718 algorithms: fix ambiguous call #4711
  algorithms/src/std_algorithms/Kokkos_NonModifyingSequenceOperations.hpp
  algorithms/src/std_algorithms/modifying_sequence_ops/Kokkos_ModifyingSequenceOperationsSet1.hpp
  algorithms/unit_tests/CMakeLists.txt
  algorithms/unit_tests/TestStdAlgorithmsCompileOnly.cpp
  algorithms/unit_tests/TestStdAlgorithmsTransformUnaryOp.cpp
Labels: Blocks Promotion

#4737 Deprecate `partition_master`, `validate_partition`
  core/src/Kokkos_HPX.hpp
  core/src/Kokkos_OpenMP.hpp
  core/src/OpenMP/Kokkos_OpenMP_Exec.cpp
  core/src/OpenMP/Kokkos_OpenMP_Exec.hpp
  core/unit_test/openmp/TestOpenMP_PartitionMaster.cpp
Labels: Blocks Promotion

#4749 Update required SYCL compiler version in CMake
  cmake/kokkos_compiler_id.cmake
Labels: Blocks Promotion

#4371 Make L1 scratch space depend on the number of teams
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Cuda/Kokkos_Cuda_Locks.cpp
  core/src/Cuda/Kokkos_Cuda_Locks.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_Locks.cpp
  core/src/HIP/Kokkos_HIP_Locks.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
Labels: Blocks Promotion

#4760 Manually compute IntelLLVM compiler version for older CMake versions
  cmake/kokkos_compiler_id.cmake
Labels: Blocks Promotion

#4770 Kokkos: Allow overloads of create_mirror_view_and_copy()
  core/src/Kokkos_CopyViews.hpp
Labels: Blocks Promotion

#4741 Unique token improvement
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_UniqueToken.hpp
  core/src/Kokkos_UniqueToken.hpp
Labels: Blocks Promotion

#4773 Fix CI on MI60
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: Bug, Blocks Promotion

#4783 Fix pre-Volta build.
  core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
  core/src/HIP/Kokkos_HIP_UniqueToken.hpp
Labels: Blocks Promotion

#4748 Update SYCL UniqueToken avoiding bitset
  core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
  core/src/HIP/Kokkos_HIP_UniqueToken.hpp
  core/src/SYCL/Kokkos_SYCL_Instance.cpp
  core/src/SYCL/Kokkos_SYCL_Instance.hpp
  core/src/SYCL/Kokkos_SYCL_UniqueToken.hpp
Labels: Blocks Promotion

#4799 Fixes for `View::operator()()`
  core/src/Kokkos_View.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestViewOperatorParens.cpp
Labels: Bug

#4804 Let `SharedAllocationHeader::get_header({void* -> void const*})`
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
Labels: Refactor

#4820 Remove duplicate `KOKKOS_IMPL_{HOST,DEVICE}_FUNCTION` macro definitions with CUDA
  core/src/setup/Kokkos_Setup_Cuda.hpp
Labels: Refactor

#4829 algorithms: remove unused kokkos::exp::move
  algorithms/src/Kokkos_StdAlgorithms.hpp
  algorithms/src/std_algorithms/Kokkos_ModifyingOperations.hpp
  algorithms/unit_tests/TestStdAlgorithmsModOps.cpp
Labels: Refactor
