Repository kokkos/kokkos, pull requests merged in 2022-01, with the labels that each got.

#4543 core/Cuda: Refactor half_t and add bhalf_t
  core/src/Cuda/Kokkos_Cuda_Half.hpp
  core/src/Kokkos_Half.hpp
  core/unit_test/TestHalfConversion.hpp
  core/unit_test/TestHalfOperators.hpp
  core/unit_test/TestReducers_d.hpp
Labels: Enhancement, Refactor

#4666 Cleanup unnecessary `#ifdef KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_HOST` guards
  containers/unit_tests/TestOffsetView.hpp
  core/src/Kokkos_TaskScheduler.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Task.cpp
  core/src/impl/Kokkos_Spinwait.cpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/TestSharedAlloc.hpp
Labels: Refactor

#4644 Disable multiple kernel instantiations when using HIP
  cmake/KokkosCore_config.h.in
  cmake/kokkos_enable_options.cmake
  core/src/HIP/Kokkos_HIP_BlockSize_Deduction.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: Blocks Promotion

#4660 Implement `KOKKOS_IF_ON_{HOST,DEVICE}` macros
  algorithms/src/Kokkos_Random.hpp
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  core/src/Cuda/Kokkos_Cuda_View.hpp
  core/src/Kokkos_Array.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_HBWSpace.hpp
  core/src/Kokkos_HPX.hpp
  core/src/Kokkos_HostSpace.hpp
  core/src/Kokkos_LogicalSpaces.hpp
  core/src/Kokkos_Macros.hpp
  core/src/Kokkos_MemoryPool.hpp
  core/src/Kokkos_NumericTraits.hpp
  core/src/Kokkos_OpenMPTargetSpace.hpp
  core/src/Kokkos_Threads.hpp
  core/src/Kokkos_View.hpp
  core/src/OpenMP/Kokkos_OpenMP_Exec.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Task.hpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
  core/src/Threads/Kokkos_ThreadsExec.hpp
  core/src/Threads/Kokkos_ThreadsTeam.hpp
  core/src/impl/Kokkos_HostBarrier.hpp
  core/src/impl/Kokkos_HostSharedPtr.hpp
  core/src/impl/Kokkos_HostThreadTeam.hpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_TaskNode.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/src/impl/Kokkos_ViewTracker.hpp
  core/unit_test/TestViewMapping_b.hpp
Labels: Blocks Promotion

#4650 Make floating_point_wrapper backend agnostic
  core/src/Cuda/Kokkos_Cuda_Half.hpp
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
  core/src/Cuda/Kokkos_Cuda_Half_Impl_Type.hpp
  core/src/Kokkos_Half.hpp
  core/src/SYCL/Kokkos_SYCL_Half_Conversion.hpp
  core/src/SYCL/Kokkos_SYCL_Half_Impl_Type.hpp
Labels: Blocks Promotion, Refactor

#4710 Reorganize includes for Kokkos_Half.hpp
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_Half.hpp
  core/src/SYCL/Kokkos_SYCL_Half_Conversion.hpp
  core/src/decl/Kokkos_Declare_CUDA.hpp
  core/src/decl/Kokkos_Declare_SYCL.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
Labels: Blocks Promotion

#4675 Avoid using execution_space as View template argument
  algorithms/src/Kokkos_Random.hpp
  containers/src/Kokkos_Bitset.hpp
  containers/src/Kokkos_ErrorReporter.hpp
  containers/src/Kokkos_UnorderedMap.hpp
  containers/src/impl/Kokkos_UnorderedMap_impl.hpp
  core/src/Kokkos_Crs.hpp
  core/src/impl/Kokkos_ViewArray.hpp
Labels: Blocks Promotion

#4704 Cap vector size to kernel maximum for SYCL
  core/src/SYCL/Kokkos_SYCL_Parallel_Team.hpp
Labels: Blocks Promotion

#4703 `kokkos_launch_compiler`: escape `$` character
  bin/kokkos_launch_compiler
Labels: Blocks Promotion

#4653 algorithms: Add bhalf rand support
  algorithms/src/Kokkos_Random.hpp
  algorithms/unit_tests/TestRandom.hpp
Labels: Feature Request, Blocks Promotion

#4724 Specify device type everywhere in Kokkos_Random.hpp
  algorithms/src/Kokkos_Random.hpp
Labels: Blocks Promotion

#4548 Add checks for shmem usage in parallel_reduce
  core/src/Cuda/Kokkos_Cuda_Parallel.hpp
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/cuda/TestCuda_ReducerViewSizeLimit.cpp
Labels: Blocks Promotion

#4694 Fix wrong device_id computation in identifier_from_devid
  core/src/impl/Kokkos_Profiling_Interface.hpp
  core/unit_test/tools/TestEventCorrectness.hpp
Labels: Blocks Promotion
