Repository kokkos/kokkos, pull requests merged in 2022-06, with the labels that each got.

#5116 Fix error message if mismatch between command line arg and env var
  core/src/impl/Kokkos_Core.cpp
Labels: Refactor

#5130 Update precedence rule in initialization
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_Profiling.cpp
  core/unit_test/TestParseCmdLineArgsAndEnvVars.cpp
Labels: Blocks Promotion

#5148 Cleanup/rework fence overloads
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/HIP/Kokkos_HIP_Space.cpp
  core/src/HPX/Kokkos_HPX.cpp
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_Cuda.hpp
  core/src/Kokkos_HIP_Space.hpp
  core/src/Kokkos_HPX.hpp
  core/src/Kokkos_OpenMP.hpp
  core/src/Kokkos_OpenMPTarget.hpp
  core/src/Kokkos_SYCL.hpp
  core/src/Kokkos_Serial.hpp
  core/src/Kokkos_Threads.hpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/SYCL/Kokkos_SYCL.cpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
  core/src/Threads/Kokkos_ThreadsExec.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_ExecSpaceInitializer.hpp
  core/src/impl/Kokkos_Serial.cpp
Labels: Refactor

#4812 MD Team Policies Implementation for serial
  core/src/Kokkos_ExecPolicy.hpp
  core/src/impl/Kokkos_HostThreadTeam.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestMDTeamParallelism.hpp
  core/unit_test/serial/TestSerial_MDTeamParallelism.cpp
Labels: Blocks Promotion

#4618 Fix failing detection of view params bugfix
  core/src/Kokkos_Layout.hpp
  core/src/Kokkos_View.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestTeamVector.hpp
  core/unit_test/TestViewCtorDimMatch.hpp
Labels: Blocks Promotion

#5141 Deprecate parallel_* overloads taking the label as later argument
  containers/performance_tests/TestScatterView.hpp
  containers/unit_tests/TestScatterView.hpp
  core/src/Kokkos_Parallel.hpp
Labels: Blocks Promotion, Deprecate
