Repository kokkos/kokkos, pull requests merged in 2022-09, with the labels that each got.

#5415 Split Random/Sort/NestedSort test into multiple cpps
  algorithms/unit_tests/CMakeLists.txt
  algorithms/unit_tests/TestNestedSort.hpp
Labels: Refactor

#5427 (Develop Only) Fixes issue 5426: spurious warning for NVCC < 11.5 about missing return statement
  core/src/Kokkos_Macros.hpp
  core/src/impl/Kokkos_ViewCtor.hpp
Labels: Compiler Issue, Ignore for CHANGELOG

#5462 Provide configure error if Kokkos_ENABLE_UNSUPPORTED_ARCHS is not set when compiling for SYCL+NVIDIA GPUs
  cmake/kokkos_arch.cmake
Labels: Bug

#5450 Move `Kokkos::reduction_identity` into its own header file
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
  core/src/HIP/Kokkos_HIP_Half_Conversion.hpp
  core/src/Kokkos_Complex.hpp
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_NumericTraits.hpp
  core/src/Kokkos_Parallel_Reduce.hpp
  core/src/Kokkos_ReductionIdentity.hpp
  core/src/SYCL/Kokkos_SYCL_Half_Conversion.hpp
  core/src/impl/Kokkos_QuadPrecisionMath.hpp
Labels: Refactor

#5289 Adding an alias for a page migrating memory space
  core/perf_test/CMakeLists.txt
  core/perf_test/test_sharedSpace.cpp
  core/src/Kokkos_Core_fwd.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestSharedSpace.cpp
Labels: Enhancement

#5497 Drop unused serial atomics
  tpls/desul/include/desul/atomics/Compare_Exchange.hpp
  tpls/desul/include/desul/atomics/Compare_Exchange_Serial.hpp
  tpls/desul/include/desul/atomics/Macros.hpp
  tpls/desul/include/desul/atomics/Thread_Fence.hpp
  tpls/desul/include/desul/atomics/Thread_Fence_Serial.hpp
Labels: Refactor

#5500 cmake: define KOKKOS_ARCH_A64FX
  cmake/KokkosCore_config.h.in
  core/src/impl/Kokkos_ViewMapping.hpp
Labels: Patch Release
