Repository kokkos/kokkos, pull requests merged in 2022-10, with the labels that each got.

#5520 Remove (unused) header `<Cuda/Kokkos_Cuda_Alloc.hpp>`
  core/src/Cuda/Kokkos_Cuda_Alloc.hpp
Labels: Refactor

#5488 Fix memory spaces in create_mirror_view overloads using view_alloc
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestCompileMain.cpp
  containers/unit_tests/TestCreateMirror.cpp
  core/src/Kokkos_CopyViews.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestCompileMain.cpp
  core/unit_test/TestCreateMirror.cpp
  core/unit_test/TestDetectionIdiom.cpp
Labels: Bug, Patch Release

#5491 Allow as_view_of_rank_n() to be overloaded for "special" scalar types
  containers/src/Kokkos_DynRankView.hpp
  core/src/Kokkos_View.hpp
Labels: Patch Release

#5525 Add support for detecting MPI local rank with MPICH
  core/src/impl/Kokkos_Core.cpp
Labels: Patch Release

#5531 fixup for intel 19 (most-vexing parse)
  core/unit_test/TestSharedHostPinnedSpace.cpp
Labels: Compiler Issue, Blocks Promotion, Failure - Nightly

#5530 Fix 5315: use Kokkos::atomic_load to Correct Race Condition Giving Rise to Seg Fault'ing Error in OpenMP tests
  core/src/Kokkos_WorkGraphPolicy.hpp
Labels: Blocks Promotion

#5528 Export the flags in KOKKOS_AMDGPU_OPTIONS when using Trilinos
  CMakeLists.txt
Labels: Patch Release

#5535 Fix static extents assignment for LayoutLeft/LayoutRight assignment
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/TestViewIsAssignable.hpp
Labels: Blocks Promotion, Patch Release

#5537 Only link against libatomic in gnu-make OpenMPTarget build
  Makefile.kokkos
Labels: Patch Release

#5532 Trilinos: Pass OpenMP flags instead of linking with the OpenMP target
  cmake/kokkos_tpls.cmake
  core/src/CMakeLists.txt
Labels: Blocks Promotion

#5540 Fix repeated team_reduce without barrier
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/HIP/Kokkos_HIP_Shuffle_Reduce.hpp
  core/unit_test/TestTeam.hpp
  core/unit_test/TestTeamReductionScan.hpp
Labels: Blocks Promotion, Patch Release

#5547 [3.7.01] #5385: Add fences to all non-exec-space sorting routines other than BinSort constructors
  algorithms/src/Kokkos_Sort.hpp
Labels: Bug, Patch Release

#5552 [3.7.01] Fix repeated team_reduce without barrier
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/HIP/Kokkos_HIP_Shuffle_Reduce.hpp
  core/unit_test/TestTeam.hpp
  core/unit_test/TestTeamReductionScan.hpp
Labels: Patch Release

#5521 [3.7.1]: Fix memory spaces in create_mirror_view overloads using view_alloc
  .jenkins
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestCompileMain.cpp
  containers/unit_tests/TestCreateMirror.cpp
  core/src/Kokkos_CopyViews.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestCompileMain.cpp
  core/unit_test/TestCreateMirror.cpp
  core/unit_test/TestDetectionIdiom.cpp
Labels: Patch Release

#5567 Fix UB in logical spaces unit test
  core/unit_test/tools/TestLogicalSpaces.hpp
Labels: Bug

#5566 [3.7.01] Fix static extents assignment for LayoutLeft/LayoutRight assignment
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/TestViewIsAssignable.hpp
Labels: Patch Release

#5569 [3.7.01] Make sure we don't add '-cuda' to the link line with NVC++
  cmake/kokkos_arch.cmake
Labels: Patch Release

#5570 [3.7.01] Add support for detecting MPI local rank with MPICH
  core/src/impl/Kokkos_Core.cpp
Labels: Patch Release

#5573 [3.7.01] Kokkos: Remove listing of undefined TPL deps (trilinos/Trilinos#11152)
  algorithms/cmake/Dependencies.cmake
  containers/cmake/Dependencies.cmake
  core/cmake/Dependencies.cmake
  simd/cmake/Dependencies.cmake
Labels: Patch Release

#5574 [3.7.01] Fixup release 3.7 chagelog drop `Kokkos::common_view_alloc_prop` from deprecated list
  CHANGELOG.md
Labels: Patch Release

#5571 [3.7.01] Export the flags in KOKKOS_AMDGPU_OPTIONS when using Trilinos
  CMakeLists.txt
Labels: Patch Release

#5441 Suppress warning: function declared with "noreturn" does return for CUDA and Debug mode
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_abort.hpp
  core/src/impl/Kokkos_Error.hpp
Labels: Blocks Promotion

#5576 Increase support to detect local MPI ranks
  core/src/impl/Kokkos_Core.cpp
Labels: Patch Release

#5555 fix incorrect offset in cuda parallel scan for < 4 byte types
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_ReduceScan.hpp
  core/unit_test/TestScan.hpp
Labels: Blocks Promotion, Patch Release
