Repository kokkos/kokkos, pull requests merged in 2022-07, with the labels that each got.

#5173 Avoid `InitArguments` in interoperability unit tests
  core/unit_test/cuda/TestCuda_InterOp_Init.cpp
  core/unit_test/cuda/TestCuda_InterOp_Streams.cpp
  core/unit_test/hip/TestHIP_InterOp_Init.cpp
  core/unit_test/hip/TestHIP_InterOp_Streams.cpp
  core/unit_test/hpx/TestHPX_InterOp.cpp
  core/unit_test/openmp/TestOpenMP_InterOp.cpp
  core/unit_test/sycl/TestSYCL_InterOp_Init.cpp
  core/unit_test/sycl/TestSYCL_InterOp_Streams.cpp
Labels: Refactor

#5174 Consolidate all HPX "IndependentInstances" unit tests into a single executable
  core/unit_test/CMakeLists.txt
  core/unit_test/hpx/TestHPX_IndependentInstances.cpp
  core/unit_test/hpx/TestHPX_IndependentInstancesDelayedExecution.cpp
  core/unit_test/hpx/TestHPX_IndependentInstancesInstanceIds.cpp
  core/unit_test/hpx/TestHPX_IndependentInstancesRefCounting.cpp
Labels: Refactor

#5179 Link libdl as interface library
  cmake/Modules/FindTPLLIBDL.cmake
  cmake/kokkos_functions.cmake
Labels: Blocks Promotion

#5170 Move min, max, clamp, minmax routines out of Experimental namespace
  algorithms/src/std_algorithms/impl/Kokkos_LexicographicalCompare.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
  core/src/Kokkos_MinMaxClamp.hpp
  core/unit_test/TestMinMaxClamp.hpp
Labels: Blocks Promotion

#5125 Provide ViewCtorProp overload for create_mirror_view_and_copy
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  containers/unit_tests/TestWithoutInitializing.hpp
  core/src/Kokkos_CopyViews.hpp
  core/unit_test/tools/TestWithoutInitializing.cpp
Labels: Blocks Promotion

#5035 Provide Kokkos::realloc overload taking Kokkos::view_alloc() return type
  containers/src/Kokkos_DualView.hpp
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_ScatterView.hpp
  containers/unit_tests/TestWithoutInitializing.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/impl/Kokkos_HostSpace_deepcopy.cpp
  core/unit_test/TestWithoutInitializing.hpp
  core/unit_test/tools/TestWithoutInitializing.cpp
Labels: Blocks Promotion

#5188 Preserve KOKKOS_INVALID_INDEX in ViewDimension and ArrayLayout construction
  core/src/Kokkos_View.hpp
  core/src/impl/Kokkos_ViewLayoutTiled.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/TestViewAPI.hpp
  core/unit_test/TestViewAPI_b.hpp
  core/unit_test/TestViewCtorDimMatch.hpp
  core/unit_test/TestViewMapping_a.hpp
Labels: Blocks Promotion

#5185 Deprecate nested types in functional
  containers/src/Kokkos_Functional.hpp
Labels: Deprecate, C++17

#5197 Fixup bug in boolean options in `InitializationSettings`
  core/src/impl/Kokkos_InitializationSettings.hpp
Labels: Bug, Blocks Promotion

#5207 Fixing issue #5196 - missing symbol with intel compiler
  core/src/Kokkos_CopyViews.hpp
Labels: Blocks Promotion

#5201 Rename tools settings for consistency
  core/src/impl/Kokkos_Command_Line_Parsing.cpp
  core/src/impl/Kokkos_Command_Line_Parsing.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_InitializationSettings.hpp
  core/src/impl/Kokkos_Profiling.cpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestInitializationSettings.cpp
Labels: Blocks Promotion

#5211 Refactor device selection at initialization
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_DeviceManagement.hpp
  core/src/impl/Kokkos_InitializationSettings.hpp
  core/unit_test/TestParseCmdLineArgsAndEnvVars.cpp
Labels: Blocks Promotion

#5167 core/unit_test: Only use even numbers in bhalf reductions
  core/unit_test/TestReducers.hpp
  core/unit_test/TestReducers_d.hpp
Labels: Bug

#5230 Raise deprecation warnings if non empty `WorkTag` class is used
  core/src/impl/Kokkos_AnalyzePolicy.hpp
  core/src/traits/Kokkos_WorkTagTrait.hpp
Labels: Blocks Promotion

#5239 Revert common view alloc prop
  containers/unit_tests/TestViewCtorPropEmbeddedDim.hpp
  core/src/Kokkos_View.hpp
  core/src/impl/Kokkos_ViewCtor.hpp
  core/unit_test/TestOther.hpp
Labels: Blocks Promotion

#5259 Restore old behavior in device selection when user specifies nothing
  core/src/impl/Kokkos_Core.cpp
Labels: Blocks Promotion

#5253 Defer gpu id validation to core
  core/src/SYCL/Kokkos_SYCL.cpp
  core/src/impl/Kokkos_Core.cpp
Labels: Enhancement, Refactor

#5256 Warn users when a flag prefixed with `-[-]kokkos` is not recognized and do not remove it
  core/src/impl/Kokkos_Command_Line_Parsing.cpp
  core/src/impl/Kokkos_Command_Line_Parsing.hpp
  core/src/impl/Kokkos_Core.cpp
  core/unit_test/TestParseCmdLineArgsAndEnvVars.cpp
Labels: Enhancement

#5250 Warn in ScopeGuard about illegal usage
  core/src/Kokkos_Core.hpp
Labels: Blocks Promotion

#5261 Fix CUDA+MSVC build issue
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/Kokkos_CudaSpace.hpp
  core/src/Kokkos_HostSpace.hpp
  core/src/impl/Kokkos_BitOps.hpp
  core/src/impl/Kokkos_FunctorAnalysis.hpp
Labels: Blocks Promotion

#5275 #5274 DynamicView: Properly resize mirror instances after construction
  containers/src/Kokkos_DynamicView.hpp
  containers/unit_tests/TestWithoutInitializing.hpp
Labels: Bug

#5278 Cherry pick fixup command line arguments handling (#5272) into RC 3.7
  core/src/impl/Kokkos_Command_Line_Parsing.cpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_Profiling.cpp
  core/unit_test/TestParseCmdLineArgsAndEnvVars.cpp
Labels: Blocks Promotion

#5276 #5274 DynamicView: Properly resize mirror instances after construction
  containers/src/Kokkos_DynamicView.hpp
  containers/unit_tests/TestWithoutInitializing.hpp
Labels: Blocks Promotion

#5292 Forward `ScopeGuard` constructor arguments to initialize
  core/src/Kokkos_Core.hpp
Labels: Refactor
