Repository kokkos/kokkos, pull requests merged in 2023-01, with the labels that each got.

#5706 Rework CUDA cache config using carveout calculations
  core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/Cuda/Kokkos_Cuda_WorkGraphPolicy.hpp
Labels: Blocks Promotion, CHANGELOG, Backend - CUDA

#5515 CTAD (deduction guides) for reducers
  core/src/Kokkos_Parallel_Reduce.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestReducerCTADs.hpp
Labels: C++17, CHANGELOG

#5687 Fix #4942 Scratch Allocation Alignment
  core/src/Kokkos_ScratchSpace.hpp
  core/src/Kokkos_View.hpp
  core/unit_test/TestTeam.hpp
Labels: Blocks Promotion, CHANGELOG

#5733 Fix -Werror with intel/19
  core/src/Kokkos_ScratchSpace.hpp
Labels: Failure - Nightly

#5731 Cleanup CUDA block size deduction
  core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp
Labels: Refactor

#5730 fix src/dst Properties in deep_copy(DynamicView,View)
  containers/src/Kokkos_DynamicView.hpp
  containers/unit_tests/TestDynamicView.hpp
Labels: Bug, Patch Release

#5763 Fix compiling with OpenMP and Kokkos_ENABLE_DEPRECATED_CODE_3
  core/src/OpenMP/Kokkos_OpenMP.hpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.hpp
Labels: Blocks Promotion

#5762 Fix ScratchSpace pointer comparison for SYCL
  core/src/Kokkos_ScratchSpace.hpp
Labels: Backend - SYCL

#5771 [4.0.0] Fix sycl scratch ptr comparison for 4.0
  core/src/Kokkos_ScratchSpace.hpp
Labels: Blocks Promotion

#5791 Remove "dead" test source files
  core/unit_test/openmp/TestOpenMP.hpp
  core/unit_test/openmptarget/TestOpenMPTarget.hpp
Labels: Refactor

#5786 Cleanup remove unused `Impl::eliminate_warning_for_lock_array()` functions
  core/src/Cuda/Kokkos_Cuda_Locks.hpp
  core/src/HIP/Kokkos_HIP_Locks.hpp
  tpls/desul/include/desul/atomics/Lock_Array_CUDA.hpp
  tpls/desul/include/desul/atomics/Lock_Array_HIP.hpp
Labels: Refactor

#5805 Fixup ROCm 5.4 `ImplForceGlobalLaunch{Launch -> }_t` typo
  core/unit_test/TestMathematicalSpecialFunctions.hpp
Labels: Bug, Blocks Promotion

#5767 Fix sycl.scratch_align test
  core/unit_test/TestTeam.hpp
Labels: Compiler Issue, Backend - SYCL

#5811 Cleanup: drop `desul_*` helper functions in tasking
  core/src/Kokkos_Atomic.hpp
  core/src/Kokkos_TaskScheduler.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_TaskNode.hpp
  core/src/impl/Kokkos_TaskQueue.hpp
  core/src/impl/Kokkos_TaskQueueCommon.hpp
  core/src/impl/Kokkos_TaskQueueMemoryManager.hpp
  core/src/impl/Kokkos_TaskQueueMultiple.hpp
  core/src/impl/Kokkos_TaskQueue_impl.hpp
Labels: Refactor

#5814 Break lock array dependence of Cuda and HIP teams impl
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
Labels: Refactor

#5819 Deprecate `KOKKOS_ACTIVE_EXECUTION_MEMORY_SPACE_*` macros
  core/src/Kokkos_Macros.hpp
Labels: Patch Release
