Repository kokkos/kokkos, pull requests merged in 2023-11, with the labels that each got.

#6575 Remove `<impl/Kokkos_Memory_Fence.hpp>` header (never included)
  core/src/impl/Kokkos_Memory_Fence.hpp
Labels: Refactor

#6545 OpenMPTarget: CI compiler upgrade.
  cmake/kokkos_compiler_id.cmake
  core/unit_test/CMakeLists.txt
  scripts/docker/Dockerfile.openmptarget
Labels: Backend - OpenMPTarget, Kokkos-Core

#6586 Desul atomics: Trade SYCL-specific compile definition for a macro defintion in the configuration header
  cmake/kokkos_arch.cmake
  core/src/Kokkos_Atomics_Desul_Config.hpp
Labels: Backend - SYCL

#6573 OpenMP: No memset in viewfill
  core/src/Kokkos_CopyViews.hpp
Labels: Performance, Kokkos-Core

#6589 Revert "Desul atomics: Trade SYCL-specific compile definition for a macro defintion in the configuration header"
  cmake/kokkos_arch.cmake
  core/src/Kokkos_Atomics_Desul_Config.hpp
Labels: Bug, Backend - SYCL

#6543 Fix infinity, quiet_NaN, signaling_Nan, isfinite, isnan, isinf for half_t and bhalf_t
  containers/unit_tests/CMakeLists.txt
  core/src/Kokkos_BitManipulation.hpp
  core/src/impl/Kokkos_Half_FloatingPointWrapper.hpp
  core/src/impl/Kokkos_Half_MathematicalFunctions.hpp
  core/src/impl/Kokkos_Half_NumericTraits.hpp
  core/unit_test/TestMathematicalFunctions.hpp
  core/unit_test/TestNumericTraits.hpp
Labels: Blocks Promotion

#6635 kokkos(profiling): do not finalize in any backend
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/Serial/Kokkos_Serial.cpp
  core/src/Threads/Kokkos_Threads_Instance.cpp
Labels: Bug
