Repository kokkos/kokkos, pull requests merged in 2023-03, with the labels that each got.

#5919 Export `Kokkos_CUDA_ARCHITECTURES` variable with CMake
  cmake/KokkosConfigCommon.cmake.in
  cmake/kokkos_arch.cmake
Labels: Enhancement, Backend - CUDA, CMake

#5925 Export `Kokkos_HIP_ARCHITECTURES` variable with CMake
  cmake/KokkosConfigCommon.cmake.in
  cmake/kokkos_arch.cmake
Labels: Enhancement, Backend - HIP, CMake

#5931 Cleanup unit_test/CMakeLists.txt
  core/unit_test/CMakeLists.txt
Labels: Refactor, CMake

#5923 Drop legacy `Impl::memory_order*`
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/impl/Kokkos_Atomic_Memory_Order.hpp
  core/src/impl/Kokkos_Atomic_View.hpp
  core/src/impl/Kokkos_ChaseLev.hpp
  core/src/impl/Kokkos_HostThreadTeam.hpp
Labels: Refactor

#5942 Tell when Kokkos atomics are disabled in print_configuration
  core/src/Serial/Kokkos_Serial.cpp
Labels: Enhancement

#5952 Drop unused `ParallelX::WorkRange` member types
  core/src/HPX/Kokkos_HPX.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
  core/src/SYCL/Kokkos_SYCL_Parallel_Scan.hpp
Labels: Refactor

#5958 Fix `OpenMPTarget::concurrency()`
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.hpp
Labels: Bug, Patch Release, Backend - OpenMPTarget

#5947 Desul atomics: drop `DESUL_HIP_RDC` compile definition
  cmake/kokkos_arch.cmake
  tpls/desul/include/desul/atomics/Lock_Array_HIP.hpp
  tpls/desul/src/Lock_Array_HIP.cpp
Labels: Backend - HIP

#5966 Make CUDA bhalf conversion code more forward compatible
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
Labels: Refactor, Backend - CUDA

#5963 Fix partition_master test
  core/unit_test/openmp/TestOpenMP_PartitionMaster.cpp
Labels: Patch Release

#5967 Bit manipulation: implement `byteswap`
  core/src/Kokkos_BitManipulation.hpp
  core/unit_test/TestBitManipulation.cpp
  core/unit_test/TestBitManipulationBuiltins.hpp
Labels: Enhancement

#5965 Desul atomics: fix bug in `desul::Impl::numeric_limits_max<uint64_t>` value
  tpls/desul/include/desul/atomics/Common.hpp
Labels: Bug, Patch Release, Backend - CUDA

#5948 Introduce `KOKKOS_IMPL_ARCH_NVIDIA_GPU` macro
  core/src/Kokkos_Macros.hpp
  core/src/OpenACC/Kokkos_OpenACC_Traits.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/SYCL/Kokkos_SYCL.cpp
  core/src/SYCL/Kokkos_SYCL_Parallel_Team.hpp
  core/src/impl/Kokkos_NvidiaGpuArchitectures.hpp
Labels: Refactor, Backend - CUDA

#6004 simd: Fixed an incorrectly returning size for uint64_t in avx2
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/unit_tests/TestSIMD.cpp
Labels: Bug

#6012 CMake: update package compatibility mode when building within Trilinos
  cmake/kokkos_install.cmake
Labels: Bug, Patch Release, CMake

#6015 Fixup 4.0 change log
  CHANGELOG.md
Labels: Patch Release
