Repository kokkos/kokkos, pull requests merged in 2023-10, with the labels that each got.

#6407 core/src: Add half single and double mixed compare (LT,GT,LE,GE)
  core/src/impl/Kokkos_Half_FloatingPointWrapper.hpp
  core/unit_test/TestHalfOperators.hpp
Labels: Bug

#6351 team-level std algos: part 13
  algorithms/src/std_algorithms/Kokkos_InclusiveScan.hpp
  algorithms/src/std_algorithms/Kokkos_TransformInclusiveScan.hpp
  algorithms/src/std_algorithms/impl/Kokkos_InclusiveScan.hpp
  algorithms/src/std_algorithms/impl/Kokkos_TransformInclusiveScan.hpp
  algorithms/unit_tests/CMakeLists.txt
  algorithms/unit_tests/TestStdAlgorithmsTeamInclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamTransformInclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTransformInclusiveScan.cpp
Labels: Blocks Promotion

#6305 #5635: Threads: Add Overloads for parallel_scan with return value for ThreadVectorRange
  core/src/Threads/Kokkos_ThreadsTeam.hpp
  core/unit_test/TestTeamVector.hpp
Labels: Blocks Promotion

#6308 #5635: SYCL: Add Overloads for parallel_scan with return value for ThreadVectorRange
  core/src/SYCL/Kokkos_SYCL_Team.hpp
  core/unit_test/TestTeamVector.hpp
Labels: Blocks Promotion

#6370 Add support for HIP Graph
  core/src/HIP/Kokkos_HIP_GraphNodeKernel.hpp
  core/src/HIP/Kokkos_HIP_GraphNode_Impl.hpp
  core/src/HIP/Kokkos_HIP_Graph_Impl.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
  core/src/HIP/Kokkos_HIP_Parallel_MDRange.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_Parallel_Team.hpp
  core/src/Kokkos_Graph.hpp
Labels: Blocks Promotion

#6487 SIMD: Split math functions from SIMD_Common.hpp
  simd/src/Kokkos_SIMD.hpp
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_Common_Math.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
Labels: Blocks Promotion

#6430 [SYCL][Reduce/Scan] Group counter should use at least memory_order::acq_rel
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_MDRange.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_Range.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_Team.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelScan_Range.hpp
Labels: Blocks Promotion

#6393 simd: add floor, ceil, round, trunc operations
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
Labels: Blocks Promotion

#6472 Update CI in OpenMPTarget to use llvm-17
  algorithms/unit_tests/CMakeLists.txt
  core/unit_test/CMakeLists.txt
  core/unit_test/TestReducers.hpp
  core/unit_test/TestReducers_b.hpp
  scripts/docker/Dockerfile.openmptarget
Labels: Backend - OpenMPTarget

#6503 team-level std algorithms: remove guards for HPX and OpenMPTarget
  algorithms/src/std_algorithms/impl/Kokkos_MustUseKokkosSingleInTeam.hpp
Labels: Blocks Promotion

#6506 Promote Kokkos_Printf.hpp to public include
  core/src/Kokkos_Abort.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_Printf.hpp
  core/src/SYCL/Kokkos_SYCL_Abort.hpp
Labels: Blocks Promotion

#6510 Kokkos_SIMD_Scalar.hpp: remove extra ';'
  simd/src/Kokkos_SIMD_Scalar.hpp
Labels: Failure - Nightly

#6525 Do not append " - blocks" to the bitset label
  containers/src/Kokkos_Bitset.hpp
  containers/src/Kokkos_UnorderedMap.hpp
  containers/src/impl/Kokkos_UnorderedMap_impl.hpp
Labels: Kokkos-Containers

#6524 Prefer defaulted default constructor for Bitset
  containers/src/Kokkos_Bitset.hpp
  containers/unit_tests/TestBitset.hpp
Labels: Performance, Kokkos-Containers
