Repository kokkos/kokkos, pull requests merged in 2023-12, with the labels that each got.

#6638 [4.2.01] Fix bug early tools finalize with non-default host execution instances
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/Serial/Kokkos_Serial.cpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
Labels: Bug

#6664 Do not negate the dependent true traits helper
  core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_MDRange.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Range.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_Team.hpp
  core/src/OpenACC/Kokkos_OpenACC_Team.hpp
  core/src/impl/Kokkos_Utilities.hpp
Labels: Refactor

#6675 Improve "deep_copy: no copy mechanism" exception message
  core/src/Kokkos_CopyViews.hpp
  core/unit_test/TestViewCopy_a.hpp
Labels: Enhancement

#6685 OpenMP: Use `omp_get_nested` for older gcc versions
  core/src/OpenMP/Kokkos_OpenMP_Instance.hpp
Labels: Compiler Issue, Kokkos-Core
