Repository kokkos/kokkos, pull requests merged in 2023-06, with the labels that each got.

#6195 Add `is_*_view` and `is_*_view_v` where missing
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  containers/src/Kokkos_ScatterView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestIsViewTrait.cpp
Labels: Documentation, CHANGELOG

#6160 [HIP] Improve heuristic deciding the number of blocks used in parallel_reduce
  core/src/HIP/Kokkos_HIP_Parallel_Range.hpp
Labels: Performance, Backend - HIP

#6223 Fix SIMD support on GPUs
  cmake/kokkos_arch.cmake
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/TestSIMD.cpp
Labels: Blocks Promotion

#6228 [4.1.00] Fix SIMD support on GPUs
  cmake/kokkos_arch.cmake
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/TestSIMD.cpp
Labels: Blocks Promotion
