Repository kokkos/kokkos, pull requests merged in 2023-04, with the labels that each got.

#5991 Desul atomics: let relocatable device code mode be part of the configuration
  Makefile.kokkos
  core/src/CMakeLists.txt
  tpls/desul/Config.hpp.cmake.in
  tpls/desul/include/desul/atomics/Lock_Array_CUDA.hpp
  tpls/desul/include/desul/atomics/Lock_Array_HIP.hpp
  tpls/desul/include/desul/atomics/Lock_Based_Fetch_Op_Unimplemented.hpp
  tpls/desul/include/desul/atomics/Macros.hpp
  tpls/desul/src/Lock_Array_CUDA.cpp
  tpls/desul/src/Lock_Array_HIP.cpp
Labels: Backend - CUDA, Backend - HIP

#6053 OpenMPTarget: Changes to Makefile.kokkos
  Makefile.kokkos
Labels: Bug, Backend - OpenMPTarget

#5692 [3.7.02] Fixes Scratch allocation alignment issues
  core/src/Kokkos_ScratchSpace.hpp
  core/src/Kokkos_View.hpp
  core/unit_test/TestTeam.hpp
Labels: Patch Release, CHANGELOG
