Repository kokkos/kokkos, pull requests merged in 2023-02, with the labels that each got.

#5832 Fix macros missing KOKKOS_ prefix, unnecessarily left defined
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/Kokkos_Crs.hpp
  core/src/Kokkos_OpenMPTargetSpace.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Error.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
  core/src/impl/Kokkos_ViewLayoutTiled.hpp
  core/src/setup/Kokkos_Setup_HIP.hpp
Labels: Bug, Patch Release, Backend - OpenMPTarget, Backend - CUDA, Backend - HIP

#5726 Refactor OpenMPTarget backend
  core/src/OpenMPTarget/Kokkos_OpenMPTarget.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Exec.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_MDRange.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Reducer.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_UniqueToken.hpp
  core/src/decl/Kokkos_Declare_OPENMPTARGET.hpp
Labels: Backend - OpenMPTarget

#5841 Desul atomics: cleanup device lock arrays
  core/src/CMakeLists.txt
  tpls/desul/include/desul/atomics/Lock_Array_CUDA.hpp
  tpls/desul/include/desul/atomics/Lock_Array_HIP.hpp
  tpls/desul/include/desul/atomics/Lock_Array_SYCL.hpp
  tpls/desul/include/desul/atomics/Macros.hpp
  tpls/desul/src/Lock_Array_CUDA.cpp
  tpls/desul/src/Lock_Array_HIP.cpp
  tpls/desul/src/Lock_Array_SYCL.cpp
Labels: Refactor

#5854 House keeping (move Serial, Threads, and Cuda headers into resp. subdirectories)
  core/src/Cuda/Kokkos_Cuda.hpp
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/Cuda/Kokkos_CudaSpace.hpp
  core/src/Cuda/Kokkos_Cuda_GraphNodeKernel.hpp
  core/src/Cuda/Kokkos_Cuda_GraphNode_Impl.hpp
  core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp
  core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
  core/src/Cuda/Kokkos_Cuda_WorkGraphPolicy.hpp
  core/src/SYCL/Kokkos_SYCL.cpp
  core/src/Serial/Kokkos_Serial.cpp
  core/src/Serial/Kokkos_Serial.hpp
  core/src/Serial/Kokkos_Serial_Task.hpp
  core/src/Threads/Kokkos_Threads.hpp
  core/src/Threads/Kokkos_Threads_WorkGraphPolicy.hpp
  core/src/decl/Kokkos_Declare_CUDA.hpp
  core/src/decl/Kokkos_Declare_SERIAL.hpp
  core/src/decl/Kokkos_Declare_THREADS.hpp
  core/src/impl/Kokkos_Default_Graph_Impl.hpp
Labels: Refactor

#5882 Deprecate `View::Rank` "uppercase R" in favor of `View::rank` "lowercase r"
  algorithms/src/Kokkos_Random.hpp
  algorithms/src/Kokkos_Sort.hpp
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_OffsetView.hpp
  containers/src/Kokkos_ScatterView.hpp
  containers/unit_tests/TestDynViewAPI.hpp
  core/perf_test/PerfTestBlasKernels.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_View.hpp
  core/unit_test/TestAggregate.hpp
  core/unit_test/TestViewMapping_a.hpp
  core/unit_test/TestViewSubview.hpp
Labels: Refactor, Deprecate

#4577 Backport bit manipulation facility from C++20 standard library header `<bit>`
  core/src/Kokkos_BitManipulation.hpp
  core/src/Kokkos_Core.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestBitManipulation.cpp
  core/unit_test/TestBitManipulationBuiltins.hpp
Labels: Refactor

#5915 Drop legacy host lock arrays
  core/src/Kokkos_HBWSpace.hpp
  core/src/Kokkos_HostSpace.hpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.hpp
  core/src/Serial/Kokkos_Serial.cpp
  core/src/Threads/Kokkos_ThreadsExec.cpp
  core/src/impl/Kokkos_HBWSpace.cpp
  core/src/impl/Kokkos_HostSpace.cpp
Labels: Refactor
