Repository kokkos/kokkos, pull requests merged in 2024-10, with the labels that each got.

#7380 Use a kernel to zero memory on mi300a
  Makefile.targets
  core/src/HIP/Kokkos_HIP_ZeroMemset.cpp
  core/src/HIP/Kokkos_HIP_ZeroMemset.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestWithoutInitializing.hpp
  core/unit_test/hip/TestHIP_UnifiedMemory_ZeroMemset.cpp
Labels: Bug, Backend - HIP

#7355 OpenMPTarget with CrayClang compiler
  algorithms/unit_tests/TestBinSortA.hpp
  algorithms/unit_tests/TestBinSortB.hpp
  algorithms/unit_tests/TestNestedSort.hpp
  algorithms/unit_tests/TestRandom.hpp
  algorithms/unit_tests/TestSort.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp
  core/unit_test/TestAtomicOperations_complexfloat.hpp
  core/unit_test/TestAtomicOperations_double.hpp
  core/unit_test/TestAtomicOperations_float.hpp
  core/unit_test/TestAtomicOperations_int.hpp
  core/unit_test/TestAtomicOperations_longint.hpp
  core/unit_test/TestAtomicOperations_longlongint.hpp
  core/unit_test/TestAtomicOperations_shared.hpp
  core/unit_test/TestAtomicOperations_unsignedint.hpp
  core/unit_test/TestAtomicOperations_unsignedlongint.hpp
  core/unit_test/TestAtomicOperations_unsignedlonglongint.hpp
  core/unit_test/TestReduce.hpp
Labels: Backend - OpenMPTarget

#7418 tests(graph): filesystem not supported by old compilers so skip these tests
  core/unit_test/cuda/TestCuda_InterOp_Graph.cpp
  core/unit_test/hip/TestHIP_InterOp_Graph.cpp
Labels: SNL-AT2-SPECIAL-APPROVAL

#7424 Enforce minimum required version for the OpenMP implementation detected at configuration time
  cmake/kokkos_tpls.cmake
Labels: CMake, Backend - OpenMP

#7428 Remove unused `impl/Kokkos_FixedBufferMemoryPool.hpp` header
  core/src/impl/Kokkos_FixedBufferMemoryPool.hpp
  core/unit_test/TestTaskScheduler.hpp
Labels: Refactor

#7433 Cleanup atomics in concurrent bitset
  core/src/impl/Kokkos_ConcurrentBitset.hpp
Labels: Refactor

#7440 CI: Enable deprecation warnings
  .appveyor.yml
  .github/workflows/continuous-integration-linux-32bit.yml
  .github/workflows/continuous-integration-linux.yml
  .github/workflows/continuous-integration-smoketest.yml
  .github/workflows/snl-ci.yml
  .jenkins
  .jenkins_nightly
  cmake/kokkos_arch.cmake
  containers/unit_tests/TestOffsetView.hpp
  core/perf_test/test_taskdag.cpp
  core/src/HPX/Kokkos_HPX_Task.hpp
  core/src/Kokkos_Future.hpp
  core/src/Kokkos_Pair.hpp
  core/src/Kokkos_TaskScheduler.hpp
  core/src/Kokkos_TaskScheduler_fwd.hpp
  core/src/OpenMP/Kokkos_OpenMP_Task.hpp
  core/src/Serial/Kokkos_Serial_Task.hpp
  core/src/Threads/Kokkos_Threads_Instance.hpp
  core/src/impl/Kokkos_MultipleTaskQueue.hpp
  core/src/impl/Kokkos_SimpleTaskScheduler.hpp
  core/src/impl/Kokkos_TaskBase.hpp
  core/src/impl/Kokkos_TaskNode.hpp
  core/src/impl/Kokkos_TaskPolicyData.hpp
  core/src/impl/Kokkos_TaskQueue.hpp
  core/src/impl/Kokkos_TaskQueueMultiple.hpp
  core/unit_test/TestArrayOps.hpp
  core/unit_test/TestTaskScheduler.hpp
  core/unit_test/incremental/Test01_execspace.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL

#7450 Revisit atomics API
  core/src/Kokkos_Atomic.hpp
  core/src/Kokkos_Atomics_Desul_Volatile_Wrapper.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
Labels: Refactor

#7458 Update atomics (deprecations + adding missing reduction ops)
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/Kokkos_Crs.hpp
  core/src/Kokkos_WorkGraphPolicy.hpp
  core/src/View/Kokkos_ViewAtomic.hpp
  core/src/impl/Kokkos_ChaseLev.hpp
  core/unit_test/TestAtomicOperations.hpp
  core/unit_test/TestSharedAlloc.hpp
  core/unit_test/TestTaskScheduler.hpp
Labels: Enhancement, Deprecate, Kokkos-Core

#7467 atomic_compare_exchange: compare fcn name typo
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/Kokkos_Macros.hpp
  core/unit_test/TestAtomicOperations.hpp
  core/unit_test/TestAtomics.hpp
Labels: Bug, Blocks Promotion

#7425 Fix OpenACC MDRangePolicy errors (issue #7403)
  core/src/OpenACC/Kokkos_OpenACC.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelFor_MDRange.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelReduce_MDRange.hpp
  core/unit_test/view/TestBasicView.hpp
Labels: Blocks Promotion

#7478 Fix wrong use of m_reducer
  core/src/Threads/Kokkos_Threads_Instance.hpp
  core/src/Threads/Kokkos_Threads_ParallelReduce_MDRange.hpp
  core/unit_test/TestReduce.hpp
Labels: Blocks Promotion

#7456 Allow using SequentialHostInit with Kokkos::DualView
  containers/src/Kokkos_DualView.hpp
  containers/unit_tests/TestDualView.hpp
Labels: Blocks Promotion

#7499 Remove `impl/Kokkos_MemoryPoolAllocator.hpp` header (never referenced)
  core/src/impl/Kokkos_MemoryPoolAllocator.hpp
Labels: Refactor
