Repository kokkos/kokkos, pull requests merged in 2024-08, with the labels that each got.

#7189 Fix atomic accessor for pre-volta GPU architectures
  core/src/Kokkos_Atomics_Desul_Volatile_Wrapper.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/Kokkos_Macros.hpp
  core/src/impl/Kokkos_DesulAtomicsConfig.hpp
Labels: Bug, Blocks Promotion, Backend - CUDA

#7192 OpenMPTarget: DeepCopy in separate file.
  core/src/OpenMPTarget/Kokkos_OpenMPTargetSpace.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_DeepCopy.hpp
Labels: Refactor, Backend - OpenMPTarget

#7200 OpenMPTarget: FunctorAdapter to centralize tag evaluation.
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_FunctorAdapter.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_MDRange.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_MDRange.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelReduce_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp
Labels: Refactor, Backend - OpenMPTarget

#7211 OpenMPTarget: FunctorAdapter bug in AMD GPU code path.
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
Labels: Bug, Backend - OpenMPTarget

#7219 Improve View for non-scalar trivial types
  core/src/View/Kokkos_ViewAlloc.hpp
Labels: Enhancement

#7224 Hands off reserved identifiers
  algorithms/src/sorting/Kokkos_BinOpsPublicAPI.hpp
  core/src/View/Kokkos_ViewAlloc.hpp
  core/unit_test/TestTeamScan.hpp
Labels: Bug

#7225 Improve further view initialization/destruction
  core/src/View/Kokkos_ViewAlloc.hpp
Labels: Enhancement, Refactor

#7228 Hide `IMPL_CUDA_MALLOC_ASYNC` option when CUDA is not enabled
  cmake/kokkos_enable_options.cmake
Labels: Backend - CUDA, Backend - HIP, CMake

#7229 Introduce new `SequentialHostInit` view allocation property
  core/src/Kokkos_View.hpp
  core/src/View/Kokkos_ViewAlloc.hpp
  core/src/impl/Kokkos_ViewCtor.hpp
  core/src/impl/Kokkos_ViewMapping.hpp
  core/unit_test/TestViewOfViews.hpp
Labels: Enhancement, Feature Request, Kokkos-Core

#7253 Fix `DynRankView::operator[](index_type)` constraint
  containers/src/Kokkos_DynRankView.hpp
Labels: Bug

#7260 Drop unused `is_space` private member types
  core/src/Kokkos_Concepts.hpp
Labels: Refactor

#7266 Prefer `std::conditional_t<T>` to `typename Impl::if_c<T>::type`
  core/src/Threads/Kokkos_Threads_Team.hpp
Labels: Refactor

#7269 Fix bogus icpc -Werror
  containers/src/Kokkos_DualView.hpp
Labels: Failure - Nightly

#6296 Add test for TeamPolicy array reduction and fix Cuda and HIP
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_ParallelReduce_Team.hpp
  core/src/HIP/Kokkos_HIP_Shuffle_Reduce.hpp
  core/unit_test/TestTeam.hpp
  core/unit_test/TestTeamReductionScan.hpp
Labels: Bug, Backend - CUDA, Backend - HIP
