Repository kokkos/kokkos, pull requests merged in 2024-12, with the labels that each got.

#7519 Always pass execution space to `Impl::DeepCopy`
  core/src/Kokkos_MemoryPool.hpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/src/impl/Kokkos_SharedAlloc_timpl.hpp
  core/unit_test/headers_self_contained/CMakeLists.txt
Labels: Refactor

#7557 build_env_info: resolve issues with ninja
  cmake/build_env_info.cmake
Labels: Failure - Trilinos, Patch Release

#7516 Deprecate StaticCrsGraph
  containers/src/Kokkos_StaticCrsGraph.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/Makefile
  containers/unit_tests/TestStaticCrsGraph.hpp
  core/unit_test/headers_self_contained/CMakeLists.txt
Labels: Deprecate, Kokkos-Containers

#7559 Update mdspan tpl to commit cb3bd4284dc3bcdfd8b7779a62ada1504fefd6a4
  tpls/mdspan/include/experimental/__p0009_bits/config.hpp
  tpls/mdspan/include/experimental/__p2630_bits/submdspan_mapping.hpp
Labels: Patch Release, SNL-CI-APPROVAL

#7566 Fixing a compiler segfault for MSVC/CUDA and a failing test.
  core/unit_test/TestAtomicViews.hpp
  core/unit_test/TestViewBadAlloc.hpp
Labels: Patch Release, SNL-CI-APPROVAL

#7564 Fix HIP clang-tidy warning in unit_tests
  containers/unit_tests/TestScatterView.hpp
  core/unit_test/TestHostSharedPtrAccessOnDevice.hpp
  core/unit_test/TestTeamBasic.hpp
  core/unit_test/hip/TestHIP_ScanUnit.cpp
  core/unit_test/hip/TestHIP_Spaces.cpp
Labels: SNL-CI-APPROVAL

#7568 Moving to nightly execution for CEA tests
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7548 Enable bugprone-implicit-widening-of-multiplication-result check with ClangTidy
  .clang-tidy
  algorithms/src/Kokkos_Random.hpp
  algorithms/unit_tests/TestSort.hpp
  algorithms/unit_tests/TestStdAlgorithmsConstraints.cpp
  containers/src/impl/Kokkos_Functional_impl.hpp
  containers/unit_tests/TestDynRankView_TeamScratch.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_ParallelFor_Team.hpp
  core/src/HIP/Kokkos_HIP_TeamPolicyInternal.hpp
  core/src/Kokkos_BitManipulation.hpp
  core/src/Kokkos_MemoryPool.hpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/OpenMP/Kokkos_OpenMP_Task.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelFor_Team.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_MDRange.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_Range.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelReduce_Team.hpp
  core/src/Threads/Kokkos_Threads_Team.hpp
  core/src/View/Kokkos_ViewMapping.hpp
  core/unit_test/TestSharedSpace.cpp
  core/unit_test/TestTaskScheduler_single.hpp
  core/unit_test/TestView_64bit.hpp
  core/unit_test/hip/TestHIP_UnifiedMemory_ZeroMemset.cpp
Labels: SNL-CI-APPROVAL

#7541 Make `build_cmake_installed_kk_as_language` example backend agnostic
  example/build_cmake_installed_kk_as_language/CMakeLists.txt
Labels: Bug, CMake, SNL-CI-APPROVAL

#7588 Update jenkins CI from ROCm 5.2 to ROCm 5.3
  .jenkins
  core/unit_test/hip/TestHIP_InterOp_Graph.cpp
Labels: SNL-CI-APPROVAL

#7592 Restrict nightly CEA build to original repo
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7563 Template MemoryPool::get_usage_statistics and print_state
  core/src/Kokkos_MemoryPool.hpp
Labels: SNL-CI-APPROVAL

#7589 Update fallback std of `nvcc_wrapper` to 17 as it is required by Kokkos
  bin/nvcc_wrapper
Labels: Backend - CUDA, SNL-CI-APPROVAL

#7580 Use cmake-format on the 'cmake.in' files
  cmake/KokkosConfig.cmake.in
  cmake/KokkosConfigCommon.cmake.in
Labels: CMake, SNL-CI-APPROVAL

#7596 Fix bugprone-switch-missing-default-case
  .clang-tidy
  algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentDifference.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamAdjacentFind.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamEqual.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamExclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamFindEnd.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamFindFirstOf.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamInclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamLexicographicalCompare.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamMismatch.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamReduce.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamSearch.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamSearchN.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamTransformExclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamTransformInclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamTransformReduce.cpp
  containers/src/impl/Kokkos_Functional_impl.hpp
  core/perf_test/test_atomic.cpp
  core/unit_test/TestAtomicOperations.hpp
  core/unit_test/TestAtomicOperations_double.hpp
  core/unit_test/TestAtomicOperations_float.hpp
  core/unit_test/TestAtomics.hpp
  core/unit_test/TestCXX11.hpp
Labels: SNL-CI-APPROVAL

#7569 core(cuda): set device not needed for stream synchronization
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
Labels: SNL-CI-APPROVAL

#7593 Use absolute value of delta in conversion test for b16
  core/unit_test/TestHalfConversion.hpp
Labels: SNL-CI-APPROVAL

#7606 Fix DynRankView performance by re-introducing shortcut operators
  containers/src/Kokkos_DynRankView.hpp
Labels: Patch Release, SNL-CI-APPROVAL

#7617 Fix CEA nightly workflow
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7602 Apply `cmake-format` on `.cmake.in` files in CI
  .github/workflows/cmake-format-check.yml
Labels: SNL-CI-APPROVAL

#7601 core(complex): constexpr
  core/src/Kokkos_Complex.hpp
  core/unit_test/TestComplex.hpp
Labels: SNL-CI-APPROVAL

#7612 Release candidate 4.5.01
  CHANGELOG.md
  CMakeLists.txt
  Makefile.kokkos
  README.md
  cmake/build_env_info.cmake
  containers/src/Kokkos_DynRankView.hpp
  core/unit_test/TestAtomicViews.hpp
  core/unit_test/TestViewBadAlloc.hpp
  scripts/docker/Dockerfile.gcc
  scripts/docker/Dockerfile.hipcc
  scripts/docker/Dockerfile.kokkosllvmproject
  scripts/docker/Dockerfile.nvcc
  scripts/docker/Dockerfile.nvhpc
  scripts/docker/Dockerfile.openmptarget
  scripts/docker/Dockerfile.sycl
  tpls/mdspan/include/experimental/__p0009_bits/config.hpp
  tpls/mdspan/include/experimental/__p2630_bits/submdspan_mapping.hpp
Labels: SNL-CI-APPROVAL

#7472 simd: refactor simd classes and hide simd_abi
  simd/src/Kokkos_SIMD.hpp
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_Common_Math.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Utilities.hpp
  simd/unit_tests/include/TestSIMD_Condition.hpp
  simd/unit_tests/include/TestSIMD_Construction.hpp
  simd/unit_tests/include/TestSIMD_Conversions.hpp
  simd/unit_tests/include/TestSIMD_GeneratorCtors.hpp
  simd/unit_tests/include/TestSIMD_MaskOps.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
  simd/unit_tests/include/TestSIMD_Reductions.hpp
  simd/unit_tests/include/TestSIMD_ShiftOps.hpp
  simd/unit_tests/include/TestSIMD_WhereExpressions.hpp
Labels: Refactor, SNL-CI-APPROVAL

#7605 Fix ViewCtorProp specialization for SequentialHostInit
  core/src/View/Kokkos_ViewCtor.hpp
  core/unit_test/TestViewCtorProp.hpp
Labels: SNL-CI-APPROVAL

#7600 core(openmp): don't forget to properly clean the `OpenMPInternal` singleton
  core/src/OpenMP/Kokkos_OpenMP_Instance.cpp
  core/src/OpenMP/Kokkos_OpenMP_Instance.hpp
Labels: SNL-CI-APPROVAL

#7619 graph(fix): nodes must be stored by the graph, whatever the backend
  core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp
  core/src/HIP/Kokkos_HIP_Graph_Impl.hpp
  core/src/SYCL/Kokkos_SYCL_Graph_Impl.hpp
  core/unit_test/TestGraph.hpp
Labels: Bug, SNL-CI-APPROVAL

#7628 [HIP] Skip mathspecialfunc_cbesselh1stkind test on MI100
  core/unit_test/TestMathematicalSpecialFunctions.hpp
Labels: SNL-CI-APPROVAL

#7620 Release 4.5.01
  CHANGELOG.md
  CMakeLists.txt
  Makefile.kokkos
  README.md
  cmake/build_env_info.cmake
  containers/src/Kokkos_DynRankView.hpp
  core/unit_test/TestAtomicViews.hpp
  core/unit_test/TestViewBadAlloc.hpp
  master_history.txt
  scripts/docker/Dockerfile.gcc
  scripts/docker/Dockerfile.hipcc
  scripts/docker/Dockerfile.kokkosllvmproject
  scripts/docker/Dockerfile.nvcc
  scripts/docker/Dockerfile.nvhpc
  scripts/docker/Dockerfile.openmptarget
  scripts/docker/Dockerfile.sycl
  tpls/mdspan/include/experimental/__p0009_bits/config.hpp
  tpls/mdspan/include/experimental/__p2630_bits/submdspan_mapping.hpp
Labels: SNL-CI-APPROVAL
