Repository kokkos/kokkos, pull requests merged in 2024-11, with the labels that each got.

#7304 Change RandomAccessIterator to avoid storing a view
  algorithms/src/sorting/Kokkos_SortPublicAPI.hpp
  algorithms/src/sorting/impl/Kokkos_SortImpl.hpp
  algorithms/src/std_algorithms/impl/Kokkos_Constraints.hpp
  algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
  algorithms/unit_tests/TestRandomAccessIterator.cpp
  algorithms/unit_tests/TestStdAlgorithmsIsSortedUntil.cpp
  algorithms/unit_tests/TestStdAlgorithmsRotate.cpp
Labels: Refactor, Performance, Kokkos-Algorithms

#7520 Remove `Impl::DynRankViewFill`
  containers/src/Kokkos_DynRankView.hpp
Labels: Refactor

#7517 Fix DynRankView in ScratchSpace
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestDynRankView_TeamScratch.hpp
Labels: Blocks Promotion

#7522 [4.5.0] Fix DynRankView in ScratchSpace (#7517)
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestDynRankView_TeamScratch.hpp
Labels: Blocks Promotion

#7518 Only use public `deep_copy` inside containers
  containers/src/Kokkos_Bitset.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_UnorderedMap.hpp
Labels: Refactor
