Repository kokkos/kokkos, pull requests merged in 2024-05, with the labels that each got.

#6965 Do not require OpenMP support for languages other than CXX
  cmake/kokkos_tpls.cmake
Labels: CMake, Backend - OpenMP

#6972 Fix use of OpenMP with Cuda or HIP as compile language
  cmake/kokkos_tpls.cmake
Labels: Bug, Backend - CUDA, Backend - HIP, CMake, Backend - OpenMP

#6962 Fix support for `Kokkos::Array` of const-qualified element type
  core/src/Kokkos_Array.hpp
  core/src/Kokkos_Swap.hpp
  core/unit_test/TestArray.cpp
Labels: Bug

#6989 Fix deprecation warnings with GCC for `pair<T1,void>` comparison operators
  core/src/Kokkos_Pair.hpp
Labels: Bug, Failure - Nightly, Deprecate

#6998 OpenMPTarget: Use mutex lock for parallel scan.
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
Labels: Bug, Backend - OpenMPTarget

#7002 Remove cuSPARSE TPL
  cmake/Dependencies.cmake
  cmake/deps/CUDA.cmake
  cmake/deps/CUSPARSE.cmake
  cmake/tpls/FindTPLCUSPARSE.cmake
Labels: Refactor, CMake

#6999 Suppress deprecated warnings via pragma push/pop in the tests
  containers/unit_tests/TestVector.hpp
  core/src/Kokkos_Macros.hpp
  core/unit_test/TestArrayOps.hpp
  core/unit_test/incremental/Test01_execspace.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
Labels: Failure - Nightly, Deprecate

#7012 Change the default execution behavior of the parallel_for(team-policy) constructs in the OpenACC backend
  core/src/OpenACC/Kokkos_OpenACC_ParallelFor_Team.hpp
  core/unit_test/CMakeLists.txt
Labels: Bug

#7016 Properly guard deprecated `Kokkos_Vector.hpp` header self contained test
  core/unit_test/headers_self_contained/CMakeLists.txt
Labels: Bug, Deprecate

#7019 Fixup for disabling deprecation warnings with NVC++
  core/src/Kokkos_Macros.hpp
Labels: Compiler Issue, Deprecate

#7023 Remove unused `CudaInternal::cuda_{malloc,free}_async_wrapper`
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
Labels: Refactor, Backend - CUDA

#7017 Improve `Impl::is_zero_byte()`
  core/src/impl/Kokkos_ViewMapping.hpp
Labels: Refactor

#6812 Only copy data in UnorderedMap deep_copy
  containers/src/Kokkos_UnorderedMap.hpp
  containers/unit_tests/TestUnorderedMap.hpp
Labels: Deprecate, Kokkos-Containers
