Repository kokkos/kokkos, pull requests merged in 2025-08, with the labels that each got.

#8291 Fix clang-tidy in the OSX CI
  .github/workflows/continuous-integration-osx.yml
Labels: SNL-CI-APPROVAL

#8290 Enable hisinf for every non bugged version of nvcc
  core/src/Cuda/Kokkos_Cuda_Half_MathematicalFunctions.hpp
Labels: SNL-CI-APPROVAL

#8321 Unset CMAKE_REQUIRED* variables after use
  cmake/Modules/FindTPLLIBQUADMATH.cmake
  cmake/kokkos_arch.cmake
Labels: CMake

#8298 Fix incompatibilities with CUDA 13 runtime API
  .jenkins/continuous.groovy
  bin/nvcc_wrapper
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
Labels: Patch Release, SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8297 Fix a warning on nvhpc
  core/unit_test/TestNumericTraits.hpp
Labels: SNL-CI-APPROVAL

#8333 Fix LegacyView to_mdspan and mdspan conversion for const
  core/src/View/Kokkos_ViewLegacy.hpp
  core/unit_test/TestMDSpanConversion.hpp
Labels: Patch Release

#8334 Cleanup `reduction_identity<complex<T>>` specialization
  core/src/Kokkos_Complex.hpp
Labels: Refactor

#8302 Test with finite math
  .github/workflows/continuous-integration-linux.yml
  core/src/Kokkos_ReductionIdentity.hpp
  core/src/impl/Kokkos_Half_ReductionIdentity.hpp
  core/src/impl/Kokkos_QuadPrecisionMath.hpp
  core/unit_test/TestMathematicalFunctions.hpp
  core/unit_test/TestMathematicalSpecialFunctions.hpp
  core/unit_test/TestNumericTraits.hpp
  core/unit_test/TestReduce.hpp
Labels: SNL-CI-APPROVAL

#8230 Factorize code in reducers to reduce code duplication
  core/src/Kokkos_Parallel_Reduce.hpp
Labels: SNL-CI-APPROVAL

#8294 Deprecate is_hostspace, is_managed, is_random_access from ViewTraits
  containers/src/Kokkos_DynRankView.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/Kokkos_View.hpp
  core/src/View/Kokkos_ViewLegacy.hpp
  core/src/View/Kokkos_ViewMapping.hpp
  core/src/View/Kokkos_ViewTracker.hpp
  core/src/View/Kokkos_ViewTraits.hpp
Labels: Deprecate, SNL-CI-APPROVAL

#8335 Cleanup `reduction_identity<__float128>` specialization
  core/src/impl/Kokkos_QuadPrecisionMath.hpp
Labels: Refactor

#8341 Mark deprecated macros in config file
  cmake/KokkosCore_config.h.in
Labels: Refactor

#8342 Move builtin reducers into their own header
  core/src/Kokkos_Parallel_Reduce.hpp
  core/src/impl/Kokkos_BuiltinReducers.hpp
Labels: Refactor

#8316 Update OpenACC parallel_scan() to support RangePolicy with non-zero begin index
  core/src/OpenACC/Kokkos_OpenACC_ParallelScan_Range.hpp
  core/unit_test/TestParallelScanRangePolicy.hpp
Labels: SNL-CI-APPROVAL

#8346 snl-ci: set KOKKOS_NUM_THREADS=64 in hpx job
  .github/workflows/snl-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#8349 Disable unsupported OpenACC atomic tests (int8_t and int16_t types)
  core/unit_test/CMakeLists.txt
  core/unit_test/TestAtomicOperations_int16.hpp
  core/unit_test/TestAtomicOperations_int8.hpp
Labels: SNL-CI-APPROVAL

#8350 Revert "ROCm 6.4: Disable -Wpass-failed warnings for some tests"
  core/unit_test/TestMathematicalSpecialFunctions.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
Labels: Backend - HIP

#8351 Disable pass-failed warning when using ROCm 6.4
  .jenkins/nightly.groovy
Labels: Backend - HIP

#8358 Fixup for DynRankView of FAD type of rank-7
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/TestDynRankView_ViewCustomization.hpp
Labels: Patch Release

#8348 Move all GitHub Actions workflows to C++20
  .github/workflows/continuous-integration-linux.yml
  .github/workflows/continuous-integration-osx.yml
  .github/workflows/continuous-integration-smoketest.yml
  .github/workflows/continuous-integration-windows.yml
  core/src/View/Kokkos_ViewTracker.hpp
  core/src/impl/Kokkos_Half_FloatingPointWrapper.hpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/unit_test/TestFunctorAnalysis.hpp
  core/unit_test/TestNumericTraits.hpp
  core/unit_test/TestSpaceAwareAccessor.hpp
  core/unit_test/TestViewEmptyRuntimeUnmanaged.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL, C++20

#8369 Drop `bin/runtest` script
  bin/runtest
Labels: Refactor

#8352 Update SNL CI to minimum C++20
  .github/workflows/snl-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL, C++20

#8372 Require C++20
  .github/workflows/codeql.yml
  .jenkins/continuous.groovy
  cmake/KokkosCore_config.h.in
  cmake/compile_tests/cplusplus20.cpp
  cmake/kokkos_arch.cmake
  cmake/kokkos_compiler_id.cmake
  cmake/kokkos_enable_devices.cmake
  cmake/kokkos_pick_cxx_std.cmake
  cmake/kokkos_test_cxx_std.cmake
Labels: SNL-AT2-SPECIAL-APPROVAL, C++20

#8370 Fix Layout Creation in DynRankView when there is a stride
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestDynRankView_LayoutMember.hpp
Labels: Bug, Patch Release
