Repository kokkos/kokkos, pull requests merged in 2025-09, with the labels that each got.

#8366 core(graph): add cuda graph on multiple gpus
  core/src/Kokkos_GraphNode.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/cuda/TestCuda_InterOp_GraphMultiGPU.cpp
Labels: SNL-CI-APPROVAL

#8382 Drop `my_std_shift_left` in algorithms tests
  algorithms/unit_tests/TestStdAlgorithmsShiftLeft.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamShiftLeft.cpp
Labels: Refactor, C++20

#8381 Drop `Impl::{type_identity,remove_cvref}[_t]`
  algorithms/src/std_algorithms/impl/Kokkos_Reduce.hpp
  containers/src/Kokkos_UnorderedMap.hpp
  core/src/Cuda/Kokkos_Cuda_GraphNodeKernel.hpp
  core/src/HIP/Kokkos_HIP_GraphNodeKernel.hpp
  core/src/Kokkos_Atomics_Desul_Wrapper.hpp
  core/src/Kokkos_ExecPolicy.hpp
  core/src/Kokkos_Graph.hpp
  core/src/Kokkos_GraphNode.hpp
  core/src/SYCL/Kokkos_SYCL_GraphNodeKernel.hpp
  core/src/View/Kokkos_ViewCtor.hpp
  core/src/impl/Kokkos_Combined_Reducer.hpp
  core/src/impl/Kokkos_GraphImpl.hpp
  core/src/impl/Kokkos_Utilities.hpp
  core/unit_test/TestConcepts.hpp
Labels: Refactor, C++20

#8379 CXX17 cleanup
  algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
  algorithms/unit_tests/TestStdAlgorithmsCompileOnly.cpp
  containers/src/Kokkos_OffsetView.hpp
  core/src/Cuda/Kokkos_Cuda_Half_MathematicalFunctions.hpp
  core/src/Kokkos_Macros.hpp
  core/src/Kokkos_View.hpp
  core/src/View/Kokkos_BasicView.hpp
  core/src/View/Kokkos_ViewLegacy.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/src/impl/Kokkos_SimpleTaskScheduler.hpp
  core/unit_test/TestMDSpan.hpp
  core/unit_test/TestMDSpanAtomicAccessor.hpp
  core/unit_test/TestSpaceAwareAccessor.hpp
  core/unit_test/TestTypeInfo.cpp
  core/unit_test/tools/TestKernelNames.cpp
Labels: Refactor, C++20

#8378 Change `Kokkos_ENABLE_DEPRECATE_CODE_4` default `ON -> OFF`
  .github/workflows/continuous-integration-smoketest.yml
  .github/workflows/continuous-integration-windows.yml
  cmake/kokkos_enable_options.cmake
Labels: CMake, SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8388 Deprecate `KOKKOS_ATTRIBUTE_NODISCARD` macro
  core/src/Kokkos_Core.hpp
  core/src/Kokkos_Macros.hpp
Labels: Refactor, Deprecate, SNL-CI-APPROVAL

#8376 Cleanup reduction identity
  core/src/Kokkos_ReductionIdentity.hpp
  core/src/impl/Kokkos_QuadPrecisionMath.hpp
Labels: Refactor

#8292 Make compile check use our linker flags
  cmake/kokkos_functions.cmake
  cmake/kokkos_tribits.cmake
Labels: Bug, Patch Release, CMake, SNL-CI-APPROVAL

#8082 Deprecate `Random_XorShift{64,1024}_Pool::init`
  algorithms/src/Kokkos_Random.hpp
Labels: Deprecate

#8377 Bump CMake minimum required version to 3.22
  .github/workflows/snl-ci.yml
  CMakeLists.txt
  example/build_cmake_in_tree/CMakeLists.txt
  example/build_cmake_installed/CMakeLists.txt
  example/build_cmake_installed_different_compiler/CMakeLists.txt
  example/build_cmake_installed_kk_as_language/CMakeLists.txt
  scripts/CTestRun.cmake
  scripts/docker/Dockerfile.hipcc
  scripts/docker/Dockerfile.nvcc
  scripts/spack_test/CMakeLists.txt
  scripts/spack_test/CMakeLists.txt.in
Labels: CMake, SNL-AT2-SPECIAL-APPROVAL

#8399 Cleanup Timer class and add tests
  core/src/Kokkos_Timer.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestTimer.hpp
Labels: Refactor

#8406 Update OpenMPTarget parallel_scan(RangePolicy) to support non-zero begin argument
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelScan_Range.hpp
  core/unit_test/TestParallelScanRangePolicy.hpp
Labels: Backend - OpenMPTarget

#8398 clang(tidy): warn for rvalues not moved
  .clang-tidy
  core/src/View/Kokkos_ViewCtor.hpp
  core/src/impl/Kokkos_Combined_Reducer.hpp
  core/src/impl/Kokkos_TeamMDPolicy.hpp
Labels: SNL-CI-APPROVAL

#8407 Drop obsolete OpenMPTarget workaround
  core/src/Kokkos_Macros.hpp
Labels: Refactor, Backend - OpenMPTarget

#8402 Check for CMake >= 3.25.2 in CUDA language builds
  cmake/kokkos_enable_options.cmake
Labels: CMake, SNL-CI-APPROVAL

#8403 Remove workarounds for older versions of CUDA/NVCC
  containers/src/Kokkos_DynRankView.hpp
  core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
  core/src/Cuda/Kokkos_Cuda_Half_Impl_Type.hpp
  core/src/Cuda/Kokkos_Cuda_Half_MathematicalFunctions.hpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Kokkos_TypeInfo.hpp
  core/src/View/Kokkos_ViewCtor.hpp
  core/unit_test/TestArray.cpp
  core/unit_test/TestGraph.hpp
  core/unit_test/TestNumericTraits.hpp
  core/unit_test/cuda/TestCuda_InterOp_Graph.cpp
Labels: Refactor, Backend - CUDA

#8423 OpenMPTarget: Remove obsolete code for non-clang compilers.
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp
Labels: Refactor, Backend - OpenMPTarget

#8392 core(cleanup): member initialization of `ParallelFor`
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_ParallelFor_Team.hpp
  core/src/HPX/Kokkos_HPX.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelFor_Team.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel_For.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_ParallelFor_Team.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelFor_Team.hpp
  core/src/Serial/Kokkos_Serial_Parallel_Team.hpp
  core/src/Threads/Kokkos_Threads_ParallelFor_Team.hpp
Labels: SNL-CI-APPROVAL

#8439 Fix RISC-V support (missing semicolon and compiler check)
  cmake/kokkos_arch.cmake
  core/src/impl/Kokkos_Core.cpp
Labels: Bug

#8463 Master release 4.7.01
  .jenkins/continuous.groovy
  CHANGELOG.md
  CMakeLists.txt
  Makefile.kokkos
  README.md
  bin/nvcc_wrapper
  cmake/kokkos_configure_trilinos.cmake
  cmake/kokkos_enable_options.cmake
  cmake/kokkos_functions.cmake
  cmake/kokkos_tribits.cmake
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestDynRankView_Ctors.hpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Kokkos_View.hpp
  core/src/View/Kokkos_ViewLegacy.hpp
  core/unit_test/TestMDSpanConversion.hpp
  core/unit_test/TestViewEmptyRuntimeUnmanaged.hpp
  master_history.txt
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8470 Drop workaround for libstdc++ 9- with rocThrust without RTTI
  cmake/kokkos_tpls.cmake
  cmake/kokkos_tribits.cmake
Labels: Refactor, Backend - HIP

#8473 Drop outdated checks for compiler versions in cmake
  cmake/kokkos_arch.cmake
  cmake/kokkos_corner_cases.cmake
  cmake/kokkos_enable_options.cmake
  cmake/kokkos_test_cxx_std.cmake
  cmake/kokkos_tribits.cmake
  core/unit_test/CMakeLists.txt
Labels: Refactor, CMake

#8478 Cleanup outdated GCC macro guards
  core/src/impl/Kokkos_QuadPrecisionMath.hpp
  core/unit_test/TestBitManipulationBuiltins.hpp
  core/unit_test/TestQuadPrecisionMath.hpp
Labels: Refactor

#8481 core(graph): an aggregate node is awaitable
  core/src/impl/Kokkos_Default_GraphNode_Impl.hpp
  core/unit_test/TestGraph.hpp
Labels: SNL-CI-APPROVAL
