Repository kokkos/kokkos, pull requests merged in 2025-02, with the labels that each got.

#7719 Unify CI dockerfiles
  scripts/docker/Dockerfile.clang
  scripts/docker/Dockerfile.gcc
  scripts/docker/Dockerfile.hipcc
  scripts/docker/Dockerfile.kokkosllvmproject
  scripts/docker/Dockerfile.nvcc
  scripts/docker/Dockerfile.nvhpc
  scripts/docker/Dockerfile.openmptarget
  scripts/docker/Dockerfile.sycl
Labels: SNL-CI-APPROVAL

#7712 DualView: Check construction from 2 Views with 1 stored
  containers/src/Kokkos_DualView.hpp
  containers/unit_tests/TestDualView.hpp
Labels: SNL-CI-APPROVAL

#7737 Remove classic intel support
  .github/workflows/continuous-integration-linux.yml
  algorithms/src/std_algorithms/impl/Kokkos_CopyIf.hpp
  algorithms/src/std_algorithms/impl/Kokkos_RandomAccessIterator.hpp
  algorithms/src/std_algorithms/impl/Kokkos_UniqueCopy.hpp
  algorithms/unit_tests/TestStdAlgorithmsCommon.hpp
  algorithms/unit_tests/TestStdAlgorithmsTeamFindIf.cpp
  algorithms/unit_tests/TestStdAlgorithmsTeamFindIfNot.cpp
  cmake/intel.cmake
  cmake/kokkos_arch.cmake
  cmake/kokkos_compiler_id.cmake
  cmake/kokkos_functions.cmake
  cmake/kokkos_test_cxx_std.cmake
  cmake/kokkos_tribits.cmake
  containers/src/Kokkos_DualView.hpp
  containers/src/Kokkos_DynRankView.hpp
  containers/src/Kokkos_DynamicView.hpp
  containers/src/Kokkos_OffsetView.hpp
  core/src/Kokkos_Complex.hpp
  core/src/Kokkos_CopyViews.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_Macros.hpp
  core/src/Kokkos_TypeInfo.hpp
  core/src/Kokkos_View.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel_For.hpp
  core/src/OpenMP/Kokkos_OpenMP_Parallel_Reduce.hpp
  core/src/View/Kokkos_ViewCtor.hpp
  core/src/View/Kokkos_ViewLegacy.hpp
  core/src/View/MDSpan/Kokkos_MDSpan_Layout.hpp
  core/src/impl/Kokkos_BitOps.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_HostSpace.cpp
  core/src/impl/Kokkos_SharedAlloc.hpp
  core/unit_test/TestArray.cpp
  core/unit_test/TestCompilerMacros.cpp
  core/unit_test/TestExecSpaceThreadSafety.hpp
  core/unit_test/TestMDRange.hpp
  core/unit_test/TestMathematicalFunctions.hpp
  core/unit_test/TestStringManipulation.cpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7741 Add Linux testing with arm64 container using clang-tidy
  .github/workflows/continuous-integration-arm64.yml
  .github/workflows/continuous-integration-stager.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#7747 Fix the macros for default simd math functions
  simd/src/Kokkos_SIMD_Common_Math.hpp
Labels: Bug, SNL-CI-APPROVAL

#7704 Use CDash for CEA nightly runs
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7765 Ease runtime xnack check
  core/src/HIP/Kokkos_HIP.cpp
  core/src/HIP/Kokkos_HIP_IsXnack.cpp
  core/src/HIP/Kokkos_HIP_IsXnack.hpp
  core/src/HIP/Kokkos_HIP_Space.cpp
Labels: SNL-CI-APPROVAL

#7767 Fix ccache usage in GitHub workflows
  .github/workflows/continuous-integration-linux.yml
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7762 Use realistic setup for CEA nightly tests
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7664 core(graph): allow construction from native graph (interop)
  core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp
  core/src/HIP/Kokkos_HIP_Graph_Impl.hpp
  core/src/Kokkos_Graph.hpp
  core/src/SYCL/Kokkos_SYCL_Graph_Impl.hpp
  core/src/impl/Kokkos_GraphImpl.hpp
  core/unit_test/cuda/TestCuda_InterOp_Graph.cpp
  core/unit_test/hip/TestHIP_InterOp_Graph.cpp
  core/unit_test/sycl/TestSYCL_InterOp_Graph.cpp
Labels: Backend - CUDA, Kokkos-Core, SNL-CI-APPROVAL

#7486 simd: add compound assignments and update reductions
  .github/workflows/snl-ci.yml
  simd/src/Kokkos_SIMD.hpp
  simd/src/Kokkos_SIMD_AVX2.hpp
  simd/src/Kokkos_SIMD_AVX512.hpp
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_Common_Math.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
  simd/unit_tests/include/TestSIMD_Construction.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
  simd/unit_tests/include/TestSIMD_Reductions.hpp
  simd/unit_tests/include/TestSIMD_ShiftOps.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7673 `print_configuration`: print support for system allocated memory
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/HIP/Kokkos_HIP.cpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_IsXnack.hpp
Labels: SNL-CI-APPROVAL

#7786 Makefile: only look for MI300X if MI300A was not found
  Makefile.kokkos
  core/src/setup/Kokkos_Setup_HIP.hpp
Labels: Bug

#7792 Allow CEA nightly build to fail
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7795 tests(hip): graph interop fix for `ROCm` 5.2
  core/unit_test/hip/TestHIP_InterOp_Graph.cpp
Labels: Backend - HIP

#7777 Extend CEA nightly tests to use C++ 20
  .github/workflows/nightly-cea.yml
  core/src/impl/Kokkos_SimpleTaskScheduler.hpp
Labels: Continuous Integration

#7809 Reduce overhead of ExecPolicy
  core/src/Kokkos_ExecPolicy.hpp
Labels: Bug, Performance, SNL-CI-APPROVAL

#7812 Remediate code scanning alert #97
  .github/workflows/codeql.yml
  .github/workflows/continuous-integration-stager.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#7813 simd: fix a bug in scalar min/max
  simd/src/Kokkos_SIMD_Common_Math.hpp
Labels: SNL-CI-APPROVAL

#7816 [HIP] Fix atomic performance bug in `atomic_fetch_op([unsigned] long*, ...)`
  .gitlab/hpsf-gitlab-ci.yml
  tpls/desul/include/desul/atomics/Fetch_Op_HIP.hpp
Labels: Bug, Performance, Backend - HIP
