Repository kokkos/kokkos, pull requests merged in 2025-04, with the labels that each got.

#7934 Prefer `bit_{ceil,floor}` to shifting left 1 by `Impl::int_log2`
  core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  core/src/HIP/Kokkos_HIP_ReduceScan.hpp
  core/src/SYCL/Kokkos_SYCL_TeamPolicy.hpp
Labels: Refactor, Backend - CUDA, Backend - HIP, Backend - SYCL

#7873 Deprecate KOKKOS_MEMORY_ALIGNMENT, KOKKOS_MEMORY_ALIGNMENT_THRESHOLD
  core/src/Kokkos_Macros.hpp
  core/src/Kokkos_MemoryTraits.hpp
  core/src/View/Kokkos_ViewMapping.hpp
Labels: SNL-CI-APPROVAL

#7954 Drop `Impl::rotate_right` in favor of `rotr`
  containers/src/Kokkos_Bitset.hpp
  containers/src/impl/Kokkos_Bitset_impl.hpp
Labels: Refactor

#7880 Fix incorrect `MDRangePolicy` iterations when the rank is higher than 4 for HIP and SYCL and improve current Cuda fix
  core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp
  core/src/HIP/Kokkos_HIP_ParallelFor_MDRange.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelFor_MDRange.hpp
  core/src/impl/KokkosExp_IterateTileGPU.hpp
  core/unit_test/TestMDRange_a.hpp
  core/unit_test/TestMDRange_b.hpp
  core/unit_test/TestMDRange_e.hpp
Labels: Bug, Enhancement, Backend - CUDA, Backend - HIP, Backend - SYCL, SNL-CI-APPROVAL

#7958 Replace assert with KOKKOS_ASSERT to fix Cuda+Clang+Debug
  algorithms/src/std_algorithms/Kokkos_SwapRanges.hpp
  algorithms/src/std_algorithms/impl/Kokkos_RemoveAllVariants.hpp
  algorithms/unit_tests/TestStdAlgorithmsTeamIsSortedUntil.cpp
  algorithms/unit_tests/TestStdAlgorithmsTransformExclusiveScan.cpp
  algorithms/unit_tests/TestStdAlgorithmsTransformInclusiveScan.cpp
  core/src/Kokkos_Tuners.hpp
  core/src/OpenMP/Kokkos_OpenMP_Task.hpp
  core/src/SYCL/Kokkos_SYCL_Instance.cpp
  core/src/SYCL/Kokkos_SYCL_Instance.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_TaskQueueMultiple.hpp
  core/unit_test/TestTaskScheduler.hpp
  core/unit_test/TestViewCopy_c.hpp
  core/unit_test/UnitTest_DeviceAndThreads.cpp
  core/unit_test/tools/TestBuiltinTuners.cpp
Labels: SNL-CI-APPROVAL

#7891 Check compiler and linker flags with CMake
  cmake/kokkos_functions.cmake
  cmake/kokkos_tribits.cmake
Labels: SNL-CI-APPROVAL

#7962 Containers: Fix unit test list with deprecated code disabled
  containers/unit_tests/CMakeLists.txt
Labels: Bug, Continuous Integration

#7957 Cleanup `deep_copy(view, val)` internals (remove duplicated `contiguous_fill_or_memset` code)
  core/src/Kokkos_CopyViews.hpp
  core/unit_test/TestWithoutInitializing.hpp
Labels: Refactor

#7976 Do not check compiler and linker flags if `kokkos_launch_compiler` is used.
  cmake/kokkos_tribits.cmake
Labels: SNL-CI-APPROVAL

#7427 View Refactor: Introduce new View implementation
  cmake/KokkosCore_config.h.in
  cmake/kokkos_enable_options.cmake
  containers/src/Kokkos_DualView.hpp
  containers/src/Kokkos_DynRankView.hpp
  containers/unit_tests/CMakeLists.txt
  containers/unit_tests/TestDynRankViewTypedefs.cpp
  core/src/Kokkos_View.hpp
  core/src/View/Kokkos_ViewTraits.hpp
  core/src/View/Kokkos_ViewUniformType.hpp
  core/src/View/MDSpan/Kokkos_MDSpan_Accessor.hpp
  core/src/View/MDSpan/Kokkos_MDSpan_Header.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestAtomicViews.hpp
  core/unit_test/TestMDSpanConversion.hpp
  core/unit_test/TestOther.hpp
  core/unit_test/TestViewIsAssignable.hpp
  core/unit_test/TestViewLayoutStrideAssignment.hpp
  core/unit_test/TestViewMapping_a.hpp
  core/unit_test/TestViewTypedefs.cpp
  core/unit_test/cuda/TestCuda_Spaces.cpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7986 snl-ci: add testing for legacy view set on/off
  .github/workflows/snl-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#7933 Clean up CUDA API wrapper
  core/src/Cuda/Kokkos_CudaSpace.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
Labels: Backend - CUDA

#7676 Check that C-style memory management before initialize or after finalize errors out
  core/src/Kokkos_Core.hpp
  core/unit_test/TestExecutionEnvironmentNonInitializedOrFinalized.cpp
Labels: SNL-CI-APPROVAL

#8005 perf(`Cuda`|`HIP`): create events with `[cuda|hip]EventDisableTiming` when timing is not needed
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
Labels: Backend - CUDA, Backend - HIP, SNL-CI-APPROVAL

#7552 core(graph): capture
  core/src/Cuda/Kokkos_Cuda_GraphNodeKernel.hpp
  core/src/Cuda/Kokkos_Cuda_Graph_Impl.hpp
  core/src/HIP/Kokkos_HIP_GraphNodeKernel.hpp
  core/src/HIP/Kokkos_HIP_Graph_Impl.hpp
  core/src/Kokkos_GraphNode.hpp
  core/src/SYCL/Kokkos_SYCL_GraphNodeKernel.hpp
  core/src/SYCL/Kokkos_SYCL_Graph_Impl.hpp
  core/src/impl/Kokkos_GraphImpl.hpp
  core/src/impl/Kokkos_GraphImpl_fwd.hpp
  core/src/impl/Kokkos_GraphNodeImpl.hpp
  core/unit_test/TestGraph.hpp
Labels: SNL-CI-APPROVAL

#8003 Enable compiler warning and -Werror for most CI builds
  .github/workflows/codeql.yml
  .github/workflows/continuous-integration-smoketest.yml
  .github/workflows/snl-ci.yml
  .gitlab/olcf-gitlab-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#8030 HIP add IsXnack.cpp to makefiles
  Makefile.targets
Labels: Bug, Backend - HIP

#8026 core(cuda): set device not needed for event synchronization
  core/src/Cuda/Kokkos_Cuda_Instance.hpp
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
Labels: Backend - CUDA, SNL-CI-APPROVAL

#8029 core(hip): set device not needed for event synchronization
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: Backend - HIP, SNL-CI-APPROVAL

#7799 Adding the basic setup of CI jobs running at NERSC nightly.
  .gitlab/nersc-gitlab-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8042 Fix memory leak from Impl::SerialInternal::singleton()
  core/src/Serial/Kokkos_Serial.cpp
Labels: Bug

#8045 Fix issue #8044
  cmake/build_env_info.cmake
Labels: SNL-CI-APPROVAL

#8047 Master release 4.6.01
  .gitlab/hpsf-gitlab-ci.yml
  CHANGELOG.md
  CMakeLists.txt
  Makefile.kokkos
  Makefile.targets
  README.md
  cmake/KokkosCore_config.h.in
  cmake/build_env_info.cmake
  cmake/compile_tests/cuda_compute_capability.cc
  cmake/kokkos_arch.cmake
  core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp
  core/src/Kokkos_Clamp.hpp
  core/src/Kokkos_Core_fwd.hpp
  core/src/Kokkos_MinMax.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_NvidiaGpuArchitectures.hpp
  core/unit_test/TestTeamTeamSize.hpp
  master_history.txt
Labels: SNL-AT2-SPECIAL-APPROVAL
