Repository kokkos/kokkos, pull requests merged in 2025-06, with the labels that each got.

#8092 Add Ampere87 (orin nano) as a valid target architecture)
  Makefile.kokkos
  cmake/KokkosCore_config.h.in
  cmake/compile_tests/cuda_compute_capability.cc
  cmake/kokkos_arch.cmake
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Instance.cpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_NvidiaGpuArchitectures.hpp
  core/unit_test/TestTeamTeamSize.hpp
  core/unit_test/TestViewAPI_e.hpp
  core/unit_test/cuda/TestCuda_DebugPinUVMSpace.cpp
Labels: SNL-CI-APPROVAL

#8094 fix(hip): constant memory launch shared resource protection with events that resist stream destruction
  core/src/HIP/Kokkos_HIP.cpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/hip/TestHIP_SharedResourceLock.cpp
Labels: SNL-CI-APPROVAL

#8118 Implement nextafter for fp16
  core/src/impl/Kokkos_Half_MathematicalFunctions.hpp
  core/unit_test/TestMathematicalFunctions.hpp
Labels: SNL-CI-APPROVAL

#8147 hpx: TeamPolicy routine updates for large number of hw threads
  .github/workflows/snl-ci.yml
  core/src/HPX/Kokkos_HPX.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8160 SYCL: Don't define FALLBACK_ASSERT
  .github/workflows/snl-ci.yml
  .gitlab/hpsf-gitlab-ci.yml
  core/src/CMakeLists.txt
  core/src/setup/Kokkos_Setup_SYCL.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL

#8192 core(graph): enforce unit launch bound
  core/src/impl/Kokkos_GraphNodeThenImpl.hpp
Labels: SNL-CI-APPROVAL

#8208 Update NERSC gitlab-ci file.
  .gitlab/nersc-gitlab-ci.yml
Labels: Failure - Nightly

#8211 Cleanup `Impl::CudaLaunchMechanism`
  core/src/Cuda/Kokkos_Cuda.hpp
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: Refactor, Backend - CUDA
