Repository kokkos/kokkos, pull requests merged in 2025-07, with the labels that each got.

#8130 GCC minimum version for cxx 20
  cmake/kokkos_compiler_id.cmake
Labels: CMake, C++20

#8220 Remove to edit CMakeCache.txt since this is bad practice
  cmake/kokkos_enable_devices.cmake
Labels: SNL-CI-APPROVAL

#8188 core(graph): fix `HIP` constant memory launch mechanism for graph node
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
  core/src/SYCL/Kokkos_SYCL_Instance.hpp
  core/unit_test/TestGraph.hpp
Labels: Backend - HIP, SNL-CI-APPROVAL

#8210 Ensure appropriate checks on subview specific View constructor
  core/src/View/Kokkos_ViewLegacy.hpp
  core/src/View/Kokkos_ViewMapping.hpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestSubView_c15.hpp
Labels: Bug

#8234 Remove Kokkos_ENABLE_IMPL_SKIP_COMPILER_MDSPAN
  .github/workflows/continuous-integration-osx.yml
  cmake/kokkos_enable_options.cmake
  core/src/CMakeLists.txt
  core/src/View/MDSpan/Kokkos_MDSpan_Header.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#8251 core(tests): using `static` for free functions in `ToolTestingUtilities` that refer to `static` variables defined in the same header
  core/unit_test/TestViewBadAlloc.hpp
  core/unit_test/tools/include/ToolTestingUtilities.hpp
Labels: SNL-CI-APPROVAL

#8248 Fix macro definition
  core/src/Kokkos_Profiling_ProfileSection.hpp
  core/src/Kokkos_Profiling_ScopedRegion.hpp
Labels: Blocks Promotion, SNL-CI-APPROVAL

#8182 Store sequential host init in unordered map
  containers/src/Kokkos_UnorderedMap.hpp
  containers/unit_tests/TestUnorderedMap.hpp
Labels: SNL-CI-APPROVAL

#8269 Cleanup zero memset in view alloc and view copy with omp
  core/src/Kokkos_CopyViews.hpp
  core/src/View/Kokkos_ViewAlloc.hpp
Labels: Refactor, Backend - OpenMP

#8273 `DualView` Guard modification flag increment against `impl_is_single_device`
  containers/src/Kokkos_DualView.hpp
  containers/unit_tests/TestDualView.hpp
Labels: SNL-CI-APPROVAL

#8243 Deprecate ViewTraits::HostMirrorSpace in favor of host_mirror_space
  core/src/View/Kokkos_ViewTraits.hpp
Labels: Deprecate

#8246 Switch to `find_last_of` to parse key value pairs in benchmarks
  core/perf_test/Benchmark_Context.cpp
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/HIP/Kokkos_HIP_Instance.cpp
  core/src/SYCL/Kokkos_SYCL.cpp
Labels: SNL-CI-APPROVAL

#8244 Correctly reduce with min/max over Views full of +inf/-inf
  core/src/Cuda/Kokkos_Cuda_Half_Conversion.hpp
  core/src/HIP/Kokkos_HIP_Half_Conversion.hpp
  core/src/Kokkos_ReductionIdentity.hpp
  core/src/SYCL/Kokkos_SYCL_Half_Conversion.hpp
  core/unit_test/TestReduce.hpp
Labels: SNL-CI-APPROVAL
