Repository kokkos/kokkos, pull requests merged in 2025-05, with the labels that each got.

#8052 OpenACC backend specialization of Random_UniqueIndex in Kokkos_Random.hpp
  algorithms/src/Kokkos_Random.hpp
  core/src/OpenACC/Kokkos_OpenACC.hpp
Labels: SNL-CI-APPROVAL

#8056 Fix spelling error in kokkos_arch.cmake
  cmake/kokkos_arch.cmake
Labels: SNL-CI-APPROVAL

#8059 Use non-default device when tesing MI300A
  .gitlab/hpsf-gitlab-ci.yml
  core/unit_test/TestDeviceAndThreads.py
Labels: Backend - HIP, Continuous Integration

#8058 Use std::numeric_limits for numeric traits
  core/src/Kokkos_NumericTraits.hpp
  core/unit_test/TestBitManipulation.cpp
Labels: Refactor

#8067 HIP architecture warning: switch to `gfx90a` in makefiles
  Makefile.kokkos
Labels: SNL-CI-APPROVAL

#8065 kokkos(tools): pass `std::string` by reference
  core/src/impl/Kokkos_Profiling.cpp
  core/src/impl/Kokkos_Profiling.hpp
Labels: SNL-CI-APPROVAL

#8073 Update bundled mdspan
  .github/workflows/mdspan-version-check.yml
  tpls/mdspan/include/experimental/__p0009_bits/compressed_pair.hpp
  tpls/mdspan/include/experimental/__p0009_bits/extents.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_left.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_right.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_stride.hpp
  tpls/mdspan/include/experimental/__p0009_bits/macros.hpp
  tpls/mdspan/include/experimental/__p0009_bits/mdspan.hpp
  tpls/mdspan/include/experimental/__p0009_bits/no_unique_address.hpp
  tpls/mdspan/include/experimental/__p0009_bits/trait_backports.hpp
  tpls/mdspan/include/experimental/__p0009_bits/type_list.hpp
  tpls/mdspan/include/experimental/__p0009_bits/utility.hpp
  tpls/mdspan/include/experimental/__p1684_bits/mdarray.hpp
  tpls/mdspan/include/experimental/__p2630_bits/strided_slice.hpp
  tpls/mdspan/include/experimental/__p2642_bits/layout_padded.hpp
  tpls/mdspan/include/experimental/__p2642_bits/layout_padded_fwd.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL

#8061 New View implementation: Disallow constructing managed View with Kokkos::MemoryUnmanaged trait
  core/src/Kokkos_View.hpp
Labels: Bug

#8077 OpenMPTarget / OpenACC: Keep locks array access in-bounds
  algorithms/src/Kokkos_Random.hpp
Labels: Backend - OpenMPTarget

#8060 An easier to maintain parallel_reduce implementation
  core/src/Kokkos_Parallel_Reduce.hpp
Labels: Refactor, Kokkos-Core, SNL-CI-APPROVAL

#8071 Avoid static variables and functions in header files.
  core/src/impl/Kokkos_Profiling_Interface.hpp
Labels: SNL-CI-APPROVAL

#8079 Exit early at initialize when the user queries the kokkos help
  core/src/impl/Kokkos_Core.cpp
  core/unit_test/CMakeLists.txt
  core/unit_test/TestKokkosHelpCausesNormalProgramTermination.cpp
Labels: Kokkos-Core

#8086 Enable bugprone-signed-char-misuse check
  .clang-tidy
  core/src/KokkosExp_MDRangePolicy.hpp
Labels: Refactor

#7807 Kokkos::SIMD::SVE support for 128-bit and 256-bit SVE
  Makefile.kokkos
  cmake/KokkosCore_config.h.in
  cmake/compile_tests/get_sve_hw_vl.cpp
  cmake/kokkos_arch.cmake
  core/src/impl/Kokkos_Core.cpp
  scripts/diff_files
  simd/src/CMakeLists.txt
  simd/src/Kokkos_SIMD.hpp
  simd/src/Kokkos_SIMD_NEON.hpp
  simd/src/Kokkos_SIMD_SVE.hpp
  simd/src/impl/Kokkos_Neon_SVE_bridge.hpp
  simd/unit_tests/include/SIMDTesting_Utilities.hpp
  simd/unit_tests/include/TestSIMD_Condition.hpp
  simd/unit_tests/include/TestSIMD_Construction.hpp
  simd/unit_tests/include/TestSIMD_Conversions.hpp
  simd/unit_tests/include/TestSIMD_GeneratorCtors.hpp
  simd/unit_tests/include/TestSIMD_MaskOps.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
  simd/unit_tests/include/TestSIMD_Reductions.hpp
  simd/unit_tests/include/TestSIMD_ShiftOps.hpp
  simd/unit_tests/include/TestSIMD_WhereExpressions.hpp
Labels: SNL-CI-APPROVAL

#8089 Enable bugprone-exception-escape check
  .clang-tidy
  algorithms/src/std_algorithms/Kokkos_IterSwap.hpp
  benchmarks/atomic/main.cpp
  benchmarks/gather/main.cpp
  benchmarks/stream/stream-kokkos.cpp
  core/src/Kokkos_Tuners.hpp
  core/src/View/Kokkos_ViewCtor.hpp
  core/src/impl/Kokkos_Combined_Reducer.hpp
  core/src/impl/Kokkos_Core.cpp
  core/src/impl/Kokkos_HostSharedPtr.hpp
  core/src/impl/Kokkos_InitializationSettings.hpp
  core/src/impl/Kokkos_SharedAlloc_timpl.hpp
  core/unit_test/UnitTest_DeviceAndThreads.cpp
  core/unit_test/tools/TestAllCalls.cpp
  example/.clang-tidy
Labels: Refactor

#8108 core(graph): allow building `Kokkos::Graph` object directly
  core/src/Kokkos_Graph.hpp
  core/src/Kokkos_GraphNode.hpp
  core/src/impl/Kokkos_GraphImpl.hpp
  core/unit_test/TestGraph.hpp
  core/unit_test/cuda/TestCuda_InterOp_Graph.cpp
  core/unit_test/hip/TestHIP_InterOp_Graph.cpp
  core/unit_test/sycl/TestSYCL_InterOp_Graph.cpp
Labels: Kokkos-Core, SNL-CI-APPROVAL
