Repository kokkos/kokkos, pull requests merged in 2025-01, with the labels that each got.

#7642 Add test for default constructed views outside execution environment lifetime
  core/unit_test/CMakeLists.txt
  core/unit_test/TestExecutionEnvironmentNonInitializedOrFinalized.cpp
Labels: SNL-CI-APPROVAL

#7647 Fix bugprone-switch-missing-default-case for NEON
  simd/src/Kokkos_SIMD_NEON.hpp
Labels: SNL-CI-APPROVAL

#7661 Use more static_asserts in TestViewMapping_a.hpp
  core/unit_test/TestViewMapping_a.hpp
Labels: SNL-CI-APPROVAL

#7652 Fix reductions with SYCL on AMD GPUs
  core/src/SYCL/Kokkos_SYCL_WorkgroupReduction.hpp
Labels: SNL-CI-APPROVAL

#7657 Fix incompatible memory space uses
  containers/unit_tests/TestOffsetView.hpp
  core/unit_test/TestTeamVector.hpp
  core/unit_test/TestViewAPI.hpp
  core/unit_test/TestViewEmptyRuntimeUnmanaged.hpp
  core/unit_test/TestViewMapping_a.hpp
  core/unit_test/TestViewMemoryAccessViolation.hpp
  core/unit_test/TestViewOutOfBoundsAccess.hpp
Labels: SNL-CI-APPROVAL

#7629 core(graph): `then` node
  core/src/Kokkos_Graph.hpp
  core/src/Kokkos_GraphNode.hpp
  core/src/impl/Kokkos_GraphImpl_fwd.hpp
  core/src/impl/Kokkos_GraphNodeThenImpl.hpp
  core/unit_test/TestGraph.hpp
Labels: SNL-CI-APPROVAL

#7609 Add test for Cuda stream semantics
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/unit_test/TestMultiGPU.hpp
  core/unit_test/cuda/TestCuda_InterOp_StreamsMultiGPU.cpp
Labels: Backend - CUDA

#7665 Use `#cmakedefine` directive for version macros in generated config file
  cmake/KokkosCore_config.h.in
Labels: Refactor, CMake, SNL-CI-APPROVAL

#7653 Add more tests for view usage violating preconditions
  core/src/View/Kokkos_BasicView.hpp
  core/src/View/Kokkos_ViewLegacy.hpp
  core/unit_test/TestExecutionEnvironmentNonInitializedOrFinalized.cpp
Labels: SNL-CI-APPROVAL

#7660 HIP: Fix default launch bound for local memory launch
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
Labels: SNL-CI-APPROVAL

#7613 Deprecate Makefile support
  Makefile.kokkos
  algorithms/unit_tests/Makefile
  benchmarks/atomic/Makefile
  benchmarks/bytes_and_flops/Makefile
  benchmarks/gather/Makefile
  benchmarks/policy_performance/Makefile
  benchmarks/stream/Makefile
  benchmarks/view_copy_constructor/Makefile
  containers/performance_tests/Makefile
  containers/unit_tests/Makefile
  core/perf_test/Makefile
  core/unit_test/Makefile
  core/unit_test/configuration/test-code/Makefile
  core/unit_test/standalone/Makefile
  example/make_buildlink/Makefile
  example/query_device/Makefile
  example/relocatable_function/Makefile
  example/tutorial/01_hello_world/Makefile
  example/tutorial/01_hello_world_lambda/Makefile
  example/tutorial/02_simple_reduce/Makefile
  example/tutorial/02_simple_reduce_lambda/Makefile
  example/tutorial/03_simple_view/Makefile
  example/tutorial/03_simple_view_lambda/Makefile
  example/tutorial/04_simple_memoryspaces/Makefile
  example/tutorial/05_simple_atomics/Makefile
  example/tutorial/06_simple_mdrangepolicy/Makefile
  example/tutorial/Advanced_Views/01_data_layouts/Makefile
  example/tutorial/Advanced_Views/02_memory_traits/Makefile
  example/tutorial/Advanced_Views/03_subviews/Makefile
  example/tutorial/Advanced_Views/04_dualviews/Makefile
  example/tutorial/Advanced_Views/05_NVIDIA_UVM/Makefile
  example/tutorial/Advanced_Views/06_AtomicViews/Makefile
  example/tutorial/Advanced_Views/07_Overlapping_DeepCopy/Makefile
  example/tutorial/Algorithms/01_random_numbers/Makefile
  example/tutorial/Hierarchical_Parallelism/01_thread_teams/Makefile
  example/tutorial/Hierarchical_Parallelism/01_thread_teams_lambda/Makefile
  example/tutorial/Hierarchical_Parallelism/02_nested_parallel_for/Makefile
  example/tutorial/Hierarchical_Parallelism/03_vectorization/Makefile
  example/tutorial/Hierarchical_Parallelism/04_team_scan/Makefile
  example/tutorial/launch_bounds/Makefile
  example/virtual_functions/Makefile
Labels: SNL-CI-APPROVAL

#7693 Don't use -fno-fortran-main in the build_cmake_installed example for flang
  example/build_cmake_installed/CMakeLists.txt
Labels: SNL-CI-APPROVAL

#7699 Avoid C-cast to void**
  core/src/Cuda/Kokkos_Cuda_Instance.cpp
  core/src/Cuda/Kokkos_Cuda_KernelLaunch.hpp
  core/src/HIP/Kokkos_HIP.cpp
  core/src/HIP/Kokkos_HIP_KernelLaunch.hpp
  core/unit_test/cuda/TestCuda_InterOp_StreamsMultiGPU.cpp
Labels: SNL-CI-APPROVAL

#7683 Fix AMD GPU auto-detect for ROCm 6.3
  cmake/kokkos_arch.cmake
Labels: SNL-CI-APPROVAL

#7669 Fix a warning from the cmake function `kokkos_check`
  cmake/KokkosConfigCommon.cmake.in
Labels: SNL-CI-APPROVAL

#7723 Include header with `xnack_enabled` only in source files that use it.
  core/src/HIP/Kokkos_HIP.cpp
  core/src/HIP/Kokkos_HIP_Instance.hpp
  core/src/HIP/Kokkos_HIP_Space.cpp
Labels: SNL-CI-APPROVAL
