Repository kokkos/kokkos, pull requests merged in 2025-03, with the labels that each got.

#7542 call thrust::inclusive_scan when available
  algorithms/CMakeLists.txt
  algorithms/perf_test/CMakeLists.txt
  algorithms/perf_test/test_inclusive_scan.cpp
  algorithms/src/std_algorithms/impl/Kokkos_InclusiveScan.hpp
  core/perf_test/BenchmarkMain.cpp
Labels: Backend - CUDA, Backend - HIP, SNL-CI-APPROVAL

#7837 Update mdspan tpl to commit 28192956b30906a8c61948268f012d6ea1ce7c2a
  .github/workflows/continuous-integration-stager.yml
  .github/workflows/mdspan-version-check.yml
  core/src/View/Kokkos_BasicView.hpp
  core/src/View/MDSpan/Kokkos_MDSpan_Accessor.hpp
  tpls/mdspan/include/experimental/__p0009_bits/compressed_pair.hpp
  tpls/mdspan/include/experimental/__p0009_bits/config.hpp
  tpls/mdspan/include/experimental/__p0009_bits/default_accessor.hpp
  tpls/mdspan/include/experimental/__p0009_bits/dynamic_extent.hpp
  tpls/mdspan/include/experimental/__p0009_bits/extents.hpp
  tpls/mdspan/include/experimental/__p0009_bits/full_extent_t.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_left.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_right.hpp
  tpls/mdspan/include/experimental/__p0009_bits/layout_stride.hpp
  tpls/mdspan/include/experimental/__p0009_bits/macros.hpp
  tpls/mdspan/include/experimental/__p0009_bits/mdspan.hpp
  tpls/mdspan/include/experimental/__p0009_bits/no_unique_address.hpp
  tpls/mdspan/include/experimental/__p0009_bits/trait_backports.hpp
  tpls/mdspan/include/experimental/__p0009_bits/type_list.hpp
  tpls/mdspan/include/experimental/__p1684_bits/mdarray.hpp
  tpls/mdspan/include/experimental/__p2630_bits/strided_slice.hpp
  tpls/mdspan/include/experimental/__p2630_bits/submdspan_mapping.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7839 Drop (unused) `Impl::power_of_two_if_valid`
  core/src/impl/Kokkos_Traits.hpp
Labels: Refactor

#7821 Make fence in Serial non blocking when Kokkos_ENABLE_ATOMICS_BYPASS is set
  core/src/Serial/Kokkos_Serial.hpp
Labels: SNL-CI-APPROVAL

#7840 Drop `Impl::integral_power_of_two[_assume_valid]()`
  containers/src/Kokkos_Bitset.hpp
  core/src/impl/Kokkos_Traits.hpp
Labels: Refactor

#7817 Reduce the overhead of tools binding during parallel_for call
  core/src/impl/Kokkos_Profiling.cpp
Labels: SNL-CI-APPROVAL

#7836 Drop `TeamPolicyInternal<{Cuda,HIP,SYCL},...>::verify_requested_vector_length()`
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_TeamPolicyInternal.hpp
  core/src/SYCL/Kokkos_SYCL_TeamPolicy.hpp
Labels: Refactor

#7853 Fixup get the concurrency from the range policy exec space instance
  .github/workflows/snl-ci.yml
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7724 Fix incorrect `MDRangePolicy` iterations when the rank is higher than 4 for Cuda
  core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp
  core/src/impl/KokkosExp_IterateTileGPU.hpp
  core/unit_test/TestMDRange.hpp
  core/unit_test/TestMDRange_a.hpp
  core/unit_test/TestMDRange_b.hpp
  core/unit_test/TestMDRange_e.hpp
Labels: Bug, Backend - CUDA, SNL-CI-APPROVAL

#7845 Fix a bug in the simd non-masked reductions and min/max functions
  simd/src/Kokkos_SIMD_Common.hpp
  simd/src/Kokkos_SIMD_Common_Math.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
  simd/unit_tests/include/TestSIMD_Reductions.hpp
Labels: SNL-CI-APPROVAL

#7830 No CUDA::cudart when compiling as CMake language
  cmake/Modules/FindTPLCUDA.cmake
Labels: Backend - CUDA, CMake, SNL-CI-APPROVAL

#7863 Add ROCm 5.6.1 build @ SNL
  .github/workflows/snl-ci.yml
Labels: SNL-AT2-SPECIAL-APPROVAL

#7831 clang 17+: use new offload driver to support RDC
  .jenkins/continuous.groovy
  cmake/kokkos_arch.cmake
  cmake/kokkos_enable_options.cmake
  core/src/Cuda/Kokkos_Cuda_Task.hpp
  core/unit_test/TestTaskScheduler_single.hpp
Labels: Backend - CUDA, CMake

#7860 Avoid pushing to the benchmark repository concurrently and archive results
  .github/workflows/performance-benchmark.yml
Labels: SNL-AT2-SPECIAL-APPROVAL, SNL-CI-APPROVAL

#7859 Build benchmarks in nightly CEA builds
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7848 Remove `Impl::is_integral_power_of_two()`
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/HIP/Kokkos_HIP_ParallelReduce_Team.hpp
  core/src/HPX/Kokkos_HPX.hpp
  core/src/Kokkos_ExecPolicy.hpp
  core/src/Kokkos_MemoryTraits.hpp
  core/src/OpenACC/Kokkos_OpenACC_ParallelScan_Range.hpp
  core/src/OpenACC/Kokkos_OpenACC_Team.hpp
  core/src/OpenMP/Kokkos_OpenMP_Team.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel.hpp
  core/src/Threads/Kokkos_Threads_Team.hpp
  core/src/impl/Kokkos_HostSpace.cpp
  core/src/impl/Kokkos_Traits.hpp
Labels: Refactor

#7870 Get the concurrency from provided execution space instances
  core/src/Cuda/Kokkos_Cuda_Parallel_Team.hpp
  core/src/Cuda/Kokkos_Cuda_UniqueToken.hpp
  core/src/HIP/Kokkos_HIP_ParallelFor_Team.hpp
  core/src/HIP/Kokkos_HIP_ParallelReduce_Team.hpp
  core/src/HIP/Kokkos_HIP_UniqueToken.hpp
  core/src/HPX/Kokkos_HPX_WorkGraphPolicy.hpp
  core/src/OpenMPTarget/Kokkos_OpenMPTarget_Parallel_Common.hpp
  core/src/SYCL/Kokkos_SYCL_UniqueToken.hpp
Labels: Bug

#7868 Improve code documentation for `MDRangePolicy` packing and unpacking for GPUs
  core/src/Cuda/Kokkos_Cuda_Parallel_MDRange.hpp
  core/src/HIP/Kokkos_HIP_ParallelFor_MDRange.hpp
  core/src/SYCL/Kokkos_SYCL_ParallelFor_MDRange.hpp
  core/src/impl/KokkosExp_IterateTileGPU.hpp
Labels: Documentation, Refactor, Backend - CUDA, Backend - HIP, Backend - SYCL, SNL-CI-APPROVAL

#7877 Add support for Zen 5 AMD microarchitecture
  Makefile.kokkos
  cmake/KokkosCore_config.h.in
  cmake/kokkos_arch.cmake
  core/src/impl/Kokkos_Core.cpp
  generate_makefile.bash
  gnu_generate_makefile.bash
Labels: SNL-CI-APPROVAL

#7892 Cuda, HIP: Fix parallel_for with more than 2^32 work items
  core/src/Cuda/Kokkos_Cuda_Parallel_Range.hpp
  core/src/HIP/Kokkos_HIP_ParallelFor_Range.hpp
Labels: SNL-CI-APPROVAL

#7898 [C++20 modules] Make sure some symbols have external linkage.
  .gitlab/hpsf-gitlab-ci.yml
  core/src/Kokkos_Core_fwd.hpp
Labels: SNL-CI-APPROVAL

#7905 Start CEA nightly tests earlier
  .github/workflows/nightly-cea.yml
Labels: Continuous Integration

#7900 Drop Impl::bit_count() in favor of popcount()
  containers/src/impl/Kokkos_Bitset_impl.hpp
  core/src/impl/Kokkos_BitOps.hpp
Labels: Refactor

#7912 Fix simd math functions not compiling when ARCH_NATIVE=ON
  simd/src/Kokkos_SIMD_Common_Math.hpp
  simd/src/Kokkos_SIMD_Scalar.hpp
  simd/unit_tests/include/SIMDTesting_Ops.hpp
  simd/unit_tests/include/SIMDTesting_Utilities.hpp
  simd/unit_tests/include/TestSIMD_MathOps.hpp
Labels: SNL-CI-APPROVAL
